### ISSUE TITLE
Variant not detekted by MIP7 / GATK in WDR62

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/MIP#1048]
This patient/DNA has now been rerun using TWIST (and WGS - still no data) and the variant in WDR62 can be detected in GATK.

https://scout.scilifelab.se/cust002/F0000310-3/478081daa1f7ab9a2b2cec715e03b4f8

// Kicki

**Comment by moonso** [comment]
Alright that sounds good!

**Comment by 47KW** [comment]
please note this one, only called by bcftools
https://scout.scilifelab.se/cust002/F0030188/5829a3ac599ee2d3acd667924b5f77b2

**Comment by henrikstranneheim** [comment]
I have keept bcftools on in the latest MIP 8 validation. Let's keep it on for now - any objections?

**Comment by KickiLagerstedt** [comment]
För vår del (Kicki & Daniel) kan vi ta bort bcftools

// Kicki

Från: Henrik Stranneheim <notifications@github.com>
Skickat: den 13 januari 2020 10:37
Till: Clinical-Genomics/MIP <MIP@noreply.github.com>
Kopia: Kristina Lagerstedt <kristina.lagerstedt@ki.se>; Author <author@noreply.github.com>
Ämne: Re: [Clinical-Genomics/MIP] Variant not detekted by MIP7 / GATK in WDR62 (#1048)


I have keept bcftools on in the latest MIP 8 validation. Let's keep it on for now - any objections?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2FMIP%2Fissues%2F1048%3Femail_source%3Dnotifications%26email_token%3DAECYPFZZAMOUUNFMUO42AELQ5QY5HA5CNFSM4I5A3HY2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIYBTXI%23issuecomment-573577693&data=02%7C01%7Ckristina.lagerstedt%40ki.se%7C6fdb30eaa8304b3a17bd08d7980c32b2%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637145050468878317&sdata=X4hQ3ZRLHfSlngeuBLw1V%2FhSDPCn%2BgPoArq%2Bs%2Fh5%2Fwk%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAECYPFZQGFQRBBNEBJAQTXDQ5QY5HANCNFSM4I5A3HYQ&data=02%7C01%7Ckristina.lagerstedt%40ki.se%7C6fdb30eaa8304b3a17bd08d7980c32b2%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637145050468878317&sdata=9H71z2V%2BBG6j1xFy2OqVFt7dzz0UWESbgFOLJ8WKVuo%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by henrikstranneheim** [comment]
The bcftools variant seems to be just another type of representation of the same variation that differs slightly from the GATK call. GATK calls variants:
```
2	73613031	218713	T	TGGA
2	73613031	403930	TGGAGGAGGAGGA	T
2	73613034	.	A	AGGT
```
In this region, which is also in GnomAD.

**Comment by henrikstranneheim** [comment]
This one: https://scout.scilifelab.se/cust002/F0000310-3/478081daa1f7ab9a2b2cec715e03b4f8
has now been resequenced with newer kit for WES and also with WGS and GATK finds it both times. Will switch off bcftools mpileup with next production release.
