### ISSUE TITLE
Test GAVIN with causative variants

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/MIP#1050]
We should run our causative variants with [GAVIN](https://molgenis20.gcc.rug.nl/menu/main/gavin-app/) and see how it behaves

**Comment by henrikstranneheim** [comment]
GAVIN does not seem to have been updated for a while still using CADD 1.3 and EXAC and only seems to support grch37.
Reading the article it is sometimes marginally better than using simply CADD and the comparison is CADD version 1.3 and using Exac. 
Will close this as it does not seem worth to implement. Please reopen if needed
