### ISSUE TITLE
Download fails for some files

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#1106]
The mip downloader repeatedly fails to download the following files for RNA

grch37_homo_sapiens_-d5-.fasta.gz
grch37_dbsnp_-138-.vcf.gz
rch38_variant_-gold_standard_dbsnp-.vcf.gz
grch38_dbsnp_-146-.vcf.gz
grch37_mills_and_1000g_-gold_standard_indels-.vcf.gz
grch37_1000g_indels_-phase1-.vcf.gz

**Comment by henrikstranneheim** [comment]
Done

**Comment by henrikstranneheim** [comment]
Done
