### ISSUE TITLE
Blacklist for vcf2cytosure

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1162]
**Is your feature request related to a problem? Please describe.**
Some regions of esp grch37 e.g. near the centromeres give rise to most of the remaining noise variants when analysing a vcf2cytosure cgh. 

**Describe the solution you'd like**
We would like to filter the vcf2cytosure variants so that we still see coverage data, but not the variant calls in the blacklist area.

**Additional context**
A tentative blacklist file has been added to the reference repo; grch38 to follow.
https://github.com/Clinical-Genomics/reference-files/blob/master/rare-disease/region/grch37_cytosure_blacklist (Sorry about the push; I was not aware I had been granted write on that repo.. 😊 )

**Comment by jemten** [comment]
I discussed the issue with @J35P312 and we think this feature is more suitable to implement in the vcf2cytosure code. To do this is MIP we would have to build a vcf parser capable of pulling out SV start, stop sites and event type. It looks like vcf2cytosure is already doing that so it should be feasible to check that against a blacklist. But I might be missing something :) 
Let me know what you think

**Comment by dnil** [comment]
Sounds doable - I kind of though you had that already, but you are right, it can be a little involved with "END"-tags and whatnot. Let's do it at vcf2cytosure.

**Comment by jemten** [comment]
Let me know when done and I will modify the MIP call to vcf2cytosure so that it can take the blacklist.

**Comment by dnil** [comment]
Done! There is now a version 0.5.0 that takes an argument ```--blacklist```. I also fixed the probe norm levels for M-M hyb so that male sex chromosomes look ok, and added a version print to log as per a veery old request.

**Comment by jemten** [comment]
Ace!

**Comment by henrikstranneheim** [comment]
@J35P312 @dnil Could you make a new singularity image for version 0.5.0?

**Comment by J35P312** [comment]
Hello there!
I have triggered build of VCF2cytosure.0.5.0, it should pop up in an hour or so!

**Comment by henrikstranneheim** [comment]
⭐️

**Comment by henrikstranneheim** [comment]
Done
