### ISSUE TITLE
STR calls in Trio

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/MIP#1169]
Good day Sir/Madam
this case shows some strange calls of STR ATXN8OS from the individuals in a trio. Example; 2019-22270-04 has 4 alleles/calls.
https://scout.scilifelab.se/cust002/F0028964-2/str/variants?variant_type=clinical#

Found by Helena Malmgren and she would appriciate to be on the issue as well.

Enjoy Wednesday

**Comment by dnil** [comment]
Ok, so we have an issue with multiallelic call splitting and family merging, possibly only in the STR path, but I would be happy if you could check the procedure for at least SVs as well.

In the case at hand, note how the 13_70713515_A_<STR20> is present on two lines with different GT calls. You could say its an issue with vt due to a problem in splitting the multi-allelics after merge - or due to a problem with SVDB not merging them into one mulitallelic line. Your call! :smile:

Having multiple lines for the same variant causes issues downstream.

```
13      70713515        .       A       <STR20> .       PASS    END=70713560;REF=15;RL=45;RU=CTG;VARID=ATXN8OS_13:70713515-70713560;REPID=ATXN8OS_13:70713515-70713560;STR_STATUS=normal        GT:SO:REPCN:REPCI:ADSP:ADFL:ADIR:LC     0/1:SPANNING/SPANNING:15/20:15-15/20-20:10/4:28/29:0/0:31.6047  ./.:.:.:.:.:.:.:.       ./.:.:.:.:.:.:.:.
13      70713515        .       A       <STR98> .       PASS    END=70713560;REF=15;RL=45;RU=CTG;VARID=ATXN8OS_13:70713515-70713560;REPID=ATXN8OS_13:70713515-70713560;STR_STATUS=full_mutation GT:SO:REPCN:REPCI:ADSP:ADFL:ADIR:LC     ./.:.:.:.:.:.:.:.       0/1:SPANNING/INREPEAT:15/98:15-15/74-118:9/0:19/37:0/16:34.708  ./.:.:.:.:.:.:.:.
13      70713515        .       A       <STR12> .       PASS    END=70713560;REF=15;RL=45;RU=CTG;VARID=ATXN8OS_13:70713515-70713560;REPID=ATXN8OS_13:70713515-70713560;OLD_MULTIALLELIC=13:70713515:A/<STR12>/<STR20>;STR_STATUS=normal GT:SO:REPCN:REPCI:ADSP:ADFL:ADIR:LC     ./.:.:.:.:.:.:.:.       ./.:.:.:.:.:.:.:.       1/.:SPANNING/SPANNING:12/20:12-12/20-20:10/7:13/19:0/0:34.5446
13      70713515        .       A       <STR20> .       PASS    END=70713560;REF=15;RL=45;RU=CTG;VARID=ATXN8OS_13:70713515-70713560;REPID=ATXN8OS_13:70713515-70713560;OLD_MULTIALLELIC=13:70713515:A/<STR12>/<STR20>;STR_STATUS=normal GT:SO:REPCN:REPCI:ADSP:ADFL:ADIR:LC     ./.:.:.:.:.:.:.:.       ./.:.:.:.:.:.:.:.       ./1:SPANNING/SPANNING:12/20:12-12/20-20:10/7:13/19:0/0:34.5446
```

**Comment by jemten** [comment]
Having looked at it I would prefer if SVDB could merge them prior to vt. I think @J35P312 said he would drop by tomorrow so we can discuss it then :)

**Comment by dnil** [comment]
Ok, I think it will actually do that rather well given that we just run vt before merge. Perhaps keep the vt after for good measure, but that is another story. Unless it's modified svdb should not be fed multiallelic calls to merge from several individuals.

**Comment by jemten** [comment]
Me and @J35P312 looked at it and it should only be a matter of switching the order of vt decompose and svdb merge. Currently we run svdb merge first and then decompose on the STR variants. 
Switching that order we get: 
```
13  70713515    .   A   <STR20> .   PASS    END=70713560;REF=15;RL=45;RU=CTG;VARID=ATXN8OS_13:70713515-70713560;REPID=ATXN8OS_13:70713515-70713560;OLD_MULTIALLELIC=13:70713515:A/<STR12>/<STR20>   GT:SO:REPCN:REPCI:ADSP:ADFL:ADIR:LC 0/1:SPANNING/SPANNING:15/20:15-15/20-20:10/4:28/29:0/0:31.6047  ./.:.:.:.:.:.:.:.   ./1:SPANNING/SPANNING:12/20:12-12/20-20:10/7:13/19:0/0:34.5446
13  70713515    .   A   <STR98> .   PASS    END=70713560;REF=15;RL=45;RU=CTG;VARID=ATXN8OS_13:70713515-70713560;REPID=ATXN8OS_13:70713515-70713560  GT:SO:REPCN:REPCI:ADSP:ADFL:ADIR:LC ./.:.:.:.:.:.:.:.   0/1:SPANNING/INREPEAT:15/98:15-15/74-118:9/0:19/37:0/16:34.708  ./.:.:.:.:.:.:.:.
13  70713515    .   A   <STR12> .   PASS    END=70713560;REF=15;RL=45;RU=CTG;VARID=ATXN8OS_13:70713515-70713560;REPID=ATXN8OS_13:70713515-70713560;OLD_MULTIALLELIC=13:70713515:A/<STR12>/<STR20>   GT:SO:REPCN:REPCI:ADSP:ADFL:ADIR:LC ./.:.:.:.:.:.:.:.   ./.:.:.:.:.:.:.:.   1/.:SPANNING/SPANNING:12/20:12-12/20-20:10/7:13/19:0/0:34.5446
```

**Comment by jemten** [comment]
Done
