### ISSUE TITLE
Phenotype: unknown vs. unaffected?

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/MIP#120]
Hi,

MIP can now run cases without affected individuals - great! :)

However, we tried with a different scenario with "unknown" phenotype and it seemed to try and run the genmod steps that fail (compounds etc.) - does MIP support running with only "unknown" sample status?

A related question: what reason is there to skip adding RankScore to these samples that are missing affected individuals? (sry if I've asked before..)

**Comment by henrikstranneheim** [comment]
If it is unknown, then MIP will be treat the samples in this case as a potentially affected sample and try to follow the normal routine i.e. run models etc as there is no better information to work upon.

I only added the unaffected track for test cases. As this is the only relevant use of running a single known to be unaffected sample through a clinical pipeline. 

MIP supports it, but genmod currently requires at least one affected sample in the pedigree file for genmod models, which also answers your related question. We should talk to Måns about this. If we want to produce a rank score for upload into Scout etc then we need to modify genmod to allow samples through for these scenarios.

**Comment by robinandeer** [comment]
Yes - then we'll set the sample as "unaffected" in the pedigree if the case contains only non-affected samples :)

It seemed like @monso thought producing rank scores should work even if the models weren't annotated - but this is not really an issue for right now

**Comment by henrikstranneheim** [comment]
Yes, but you would need to modify the rank model file since the vcf will not contain the geneticModel key to run score and then compounds would not be able to run either since models was not run. It becomes complicated quite fast. 

An easier approach is to relax genmod for "unknown" samples - @moonso: if possible. As you said, let's fix this another time.
