### ISSUE TITLE
peculiar allele depth

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/MIP#1245]
Just noticed that when a case is having a genotype that does not include the reference allele, the allele depth gets weird. (-1 / -1)
https://scout.scilifelab.se/cust002/F0032567/26af0d949867a9b7d5b49596e48d1978

"An issue a day, keeps the bioinformatician at work"

**Comment by dnil** [comment]
Looks like a failed normalisation, or possibly a new-ish limitation in GATK?
Scout db accurately reflects a lack of AD in the VCF, though that could perhaps be presented in a bit more user (and superuser) friendly fashion than '-1/-1'.

<img width="289" alt="Screenshot 2019-12-06 at 11 48 33" src="https://user-images.githubusercontent.com/758570/70317645-7210a380-181e-11ea-8a37-351a49b57a02.png">

The call should be G -> T/A, which I think GATK did. The vt norm took it apart into G->T which is actually wild type, and G->A which is the one we are looking at. Now AD is missing. All the way from GATK, or only after vt?

<img width="1668" alt="Screenshot 2019-12-06 at 11 58 37" src="https://user-images.githubusercontent.com/758570/70318565-a71df580-1820-11ea-8174-27e5e21d0962.png">

**Comment by henrikstranneheim** [comment]
Seems to be all the way from GATK:
```
19	10116375	rs2303099	G	A,T	1350.02	PASS	AC=1,0;AF=0.5,0;AN=2;DB;DP=138;POSITIVE_TRAIN_SITE;set=Intersection	GT:DP:GQ	1/0:34:99
```
I do not think MIP can do anything about this - or what do you think @dnil

**Comment by dnil** [comment]
I'm not sure. GATK *used* to provide AD also for multiallelics more or less per default as I recall it, but then I haven't run much manually for a long time now, so not sure if they just discontinued it, or some option is required in some step to reenable it. Don't we get AD for any multis right now?

**Comment by henrikstranneheim** [comment]
It looks like it comes from combining bcftools and GATK for multiallelics where one alt allele comes from bcftools:
Only GATK:
```
1       153874333       rs7516574       T       A       4156.71 PASS    AC=3;AF=0.5;AN=6;DB;DP=104;ExcessHet=3.0103;FS=0;MLEAC=3;MLEAF=0.5;MQ=59.95;QD=33.08;SOR=0.836;VQSLOD=4.86;culprit=DP   GT:AD:DP:GQ:PL  1/0:0,6:21:99:1524,668,598      1/0:0,4:11:99:957,313,259       1/0:0,12:26:99:1698,621,536
1       153874333       rs7516574       T       TA      4156.71 PASS    AC=3;AF=0.5;AN=6;DB;DP=104;ExcessHet=3.0103;FS=0;MLEAC=3;MLEAF=0.5;MQ=59.95;QD=33.08;SOR=0.836;VQSLOD=4.86;culprit=DP   GT:AD:DP:GQ:PL  0/1:0,15:21:99:1524,281,197     0/1:0,7:11:99:957,204,147       0/1:0,14:26:99:1698,538,459
```
GATK and bcftools after combine:
```
1       153874333       rs7516574       T       A       6994.71 PASS    AC=3;AF=0.500;AN=6;DB;DP=357;set=Intersection   GT:AD:DP:GQ:PL  1/0:0,13:32:99:2143,847,745     1/0:0,18:39:99:2458,923,803     1/0:0,14:33:99:2416,843,714
1       153874333       rs7516574       T       TA,TAATA        6994.71 PASS    AC=3,0;AF=0.500,0.00;AN=6;DB;DP=357;INDEL;set=Intersection      GT:DP:GQ        0/1:32:99       0/1:39:99       0/1:33:99
```

If we turn of bcftools this problem will go away....

**Comment by dnil** [comment]
That makes a lot more sense! Thanks! Ok, so disabling bcftools would solve it out of the box.. Otw one would have to fiddle with the combine calls. They are supposed to use GATK for default, aren't they?

**Comment by henrikstranneheim** [comment]
They are and they do, as far as I know except for this special case

**Comment by henrikstranneheim** [comment]
We will turn off bcftools mpileup in the next production release. That will solve this problem. Thanks for reporting!
