### ISSUE TITLE
Include SMNCopyNumberCaller

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1290]
**Is your feature request related to a problem? Please describe.**
We have heard the rumours and been waiting eagerly, but now it's official: 
[SMNCopyNumberCaller](https://github.com/Illumina/SMNCopyNumberCaller). Good-enough:ish performance - really nice, given the difficulty level of doing this with short reads. See [preprint](https://www.medrxiv.org/content/10.1101/19006635v2).

**Describe the solution you'd like**
Include in MIP. Export annotation for Scout - need to figure out if we should load the json directly, or e.g. convert to vcf.

**Comment by henrikstranneheim** [comment]
That´s great! Let´s discuss how to deliver the result before starting an implementation.

**Comment by dnil** [comment]
Sure! I'll tentatively be around Wednesday. The tool was reasonably straightforward to install, and runs quickly. This is a blockbuster application, so if anyone has time to add it to MIP that is surely going to be worth it. If you just make sure the resulting small tsv or json gets forwarded to scout, we can take it from there. I suppose it will end up on its own view again, to make sure no-one sees it unless they really wanted to.

**Comment by dnil** [comment]
We've found one carrier out of two suspicious cases screened..

**Comment by henrikstranneheim** [comment]
I will start adding it asap

**Comment by dnil** [comment]
:+1: 
"Population-wide SMA screening to quantify the SMN1 copy number (CN) is recommended by the American College of Medical Genetics." 👀

**Comment by henrikstranneheim** [comment]
MIP can now run SMNCopyNumberCaller on each gatk_baserecalibrated sample BAM and produce the ".tsv" file.
