### ISSUE TITLE
rhocall / UPD file naming confusion

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1310]
**Describe the bug**
In the current validation version (from /home/proj/stage/rare-disease/mip/validation/191217,  MIP Version: v8.0.0) rhocall wig and bed do not appear. 

Can be enabled with ```rhocall viz --wig --out_dir rhocall --aftag GNOMADAF --rho case_sorted_md_brecal_haptc_vrecal_comb_BOTH.roh case_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_frqf_vep_parsed_snpeff_ranked_BOTH.vcf``` or such.

Also, the UPD.py output bed files (region, sites) are somewhat unexpectedly named "rhocall" and lack a .bed ending.

Just ignore if it is already fixed in the develop-branch.. Thanks!

**Comment by henrikstranneheim** [comment]
This is what it looks like now:
**Chromograph**
Tar dir:
<img width="931" alt="Screenshot 2020-02-21 at 11 39 46" src="https://user-images.githubusercontent.com/584738/75027571-1067e900-549f-11ea-9506-09ce7372d401.png">

**Rhocall_viz**
<img width="1198" alt="Screenshot 2020-02-21 at 11 42 22" src="https://user-images.githubusercontent.com/584738/75027779-6d639f00-549f-11ea-8705-cfaa1c311f5c.png">

@dnil and @mikaell Are we missing anything?

**Comment by dnil** [comment]
At least the upd big bed are made and named something. Promising! And rhocall now appears to produce bed and get a bigwig made. Nice! 👍🏻 That about covers the issue, doesn’t it!

To specifically anser the question, it’s hard to tell if sth is missing from partial pictures? 😊 But, if you ask me to guess based on what I see, I get the feeling some chromograph files are not produced. Can I find a reasonably new run in the same place to check?

**Comment by henrikstranneheim** [comment]
I added the complete picture now. I do not have run using develop on stage right now, but I guess we will have in the near future. So far so good then..closing

**Comment by dnil** [comment]
Ok, thanks! It looks like at least the ideogram pictures are missing, but let’s open a separate issue with details on that!

**Comment by henrikstranneheim** [comment]
👍
