### ISSUE TITLE
Telomere length from wgs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1324]
**Is your feature request related to a problem? Please describe.**

In certain conditions, both rd and cancer, knowing telomere lengths can be informative in combination with germline changes to certain genes. Telomere length can be estimated from wgs data, eg by [Telomerecat](https://www.nature.com/articles/s41598-017-14403-y) - available open source GPL3 https://github.com/jhrf/telomerecat 
https://telomerecat.readthedocs.io/

**Describe the solution you'd like**
Consider adding telomerecat or a similar tool to the pipeline. While only important for some patients, it seems to run fairly quickly, and we’d ideally like to avoid having little extra packages to run on the side.

**Comment by jemten** [comment]
@dnil, I have stared working on adding telomerecat to MIP. I have written it to output a single csv file for the entire family. It looks like this for a test sample:
```
Sample,F1,F2,F4,Psi,Insert_mean,Insert_sd,Read_length,Initial_read_length,F2a,F2a_c,Length
NA12877-200M,4116,1298,605,1.42,383.691,84.45700000000001,151,151,693,693,1754.5
NA12882-200M,20761,2348,1470,2.01,380.12199999999996,90.064,151,151,878,878,5866.3
NA12878-200M,9984,1354,976,1.746,374.98900000000003,85.76700000000001,151,151,378,378,6347.7
```
Does this look OK to you or is beneficial to have the length estimates for each chromosome separately?

**Comment by dnil** [comment]
Very cool!

I think this was pretty much what I intended. I can't remember seeing data for each chr? How did you get that?

Anyway, next step would then be to test, and prep for display in e.g. Scout.

I have gathered a small set of sample IDs for samples w/ defects in teleomere maintainenance for a test. If you want, I can perhaps email you with them? Or I could run them separately and discuss, if there was no issues with the installation on hasta.

**Comment by jemten** [comment]
> Very cool!
> 
> I think this was pretty much what I intended. I can't remember seeing data for each chr? How did you get that?

I spoke too soon. Thought that I could run the program with bam files splitted on chromosome. Turns out that that's not how it works.

> 
> Anyway, next step would then be to test, and prep for display in e.g. Scout.
> 
> I have gathered a small set of sample IDs for samples w/ defects in teleomere maintainenance for a test. If you want, I can perhaps email you with them? Or I could run them separately and discuss, if there was no issues with the installation on hasta.

Some test cases would be excellent! Send me the IDs and I'll test. There was a docker container [available](https://quay.io/repository/wtsicgp/telomerecat) so installation was simple so the installation is simple if you want to run them yourself.

**Comment by jemten** [comment]
This has been implemented. The calling seems a little shaky but it'll do for now
