### ISSUE TITLE
wigToBigWig

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1327]
**Is your feature request related to a problem? Please describe.**
Large wig's load slowly in igv. Convert wigs for display to bigwig (rhocall, TIDDIT).
Similarly with the largest bed files. UPD-sites-bed would thus need conversion to bigBED.

**Describe the solution you'd like**
Use wigToBigWig or similar to convert wig files into bigwig, and bed to bigbed with bedToBigBed.

**Comment by henrikstranneheim** [comment]
Added docker:
 - ucsc with wigToBigWig and bedToBigBed tools
Added sub for producing chromosome size file to be used with tools

**Comment by henrikstranneheim** [comment]
@dnil and @J35P312 
Is it this file `ACC5339A2_lanes_1234_sorted_md_brecal_tcov.wig`that should get a corresponding index from the tiddit_coverage recipe:
`
TIDDIT.py --cov -o livingox_cyto_tiddit_ACC5339A2 -z 500 -w --bam ACC5339A2_lanes_1234_sorted_md_brecal.bam`

Is it this file `output.wig`that should get a corresponding index from the rhocall_viz recipe:
`
rhocall viz --aftag GNOMADAF --out_dir rhocall_viz --rho livingox_gatkcomb_rhocall_vt_af.ACC5339A2.roh --wig livingox_gatkcomb_rhocall_vt_af.ACC5339A2.vcf
`

Is it this file `livingox_gatkcomb_rhocall_vt_af_upd.sites.bed`that should get a corresponding index from the upd recipe:
`upd --af-tag GNOMADAF --vcf livingox_gatkcomb_rhocall_vt_af.vcf.gz --proband ACC5339A4 --mother ACC5339A3 --father ACC5339A2 sites --out livingox_gatkcomb_rhocall_vt_af_upd.sites.bed`

**Comment by henrikstranneheim** [comment]
@dnil Bump

**Comment by dnil** [comment]
> @dnil and @J35P312
> Is it this file `ACC5339A2_lanes_1234_sorted_md_brecal_tcov.wig`that should get a corresponding index from the tiddit_coverage recipe:
> ` TIDDIT.py --cov -o ACC5339A2_lanes_1234_sorted_md_brecal_tcov -z 500 -w --bam ACC5339A2_lanes_1234_sorted_md_brecal.bam`

Looks good! 

> 
> Is it this file `output.wig`that should get a corresponding index from the rhocall_viz recipe:
> `rhocall viz --aftag GNOMADAF --out_dir rhocall_viz --rho livingox_gatkcomb_rhocall_vt_af.ACC5339A2.roh --wig livingox_gatkcomb_rhocall_vt_af.ACC5339A2.vcf`

Yep!

> Is it this file `livingox_gatkcomb_rhocall_vt_af_upd.sites.bed`that should get a corresponding index from the upd recipe:
> `upd --af-tag GNOMADAF --vcf livingox_gatkcomb_rhocall_vt_af.vcf.gz --proband ACC5339A4 --mother ACC5339A3 --father ACC5339A2 sites --out livingox_gatkcomb_rhocall_vt_af_upd.sites.bed`

Yes!

**Comment by henrikstranneheim** [comment]
👍 Thx!

**Comment by henrikstranneheim** [comment]
@dnil @J35P312 : Are you following the wig format with TIDDIT? I get these errors:
1
<img width="1434" alt="Screenshot 2020-02-11 at 12 20 42" src="https://user-images.githubusercontent.com/584738/74232448-1accfa80-4cc9-11ea-8d5b-3a9213752597.png">
2. using `wigToBigWig -clip /home/henrik.stranneheim/develop/livingox/analysis_grch37/ACC5339A3/tiddit_coverage/ACC5339A3_lanes_1234_sorted_md_brecal_tcov.wig /home/henrik.stranneheim/develop/118/analysis/118-1-2A/tiddit_coverage/contigs_size_file.tsv ACC5339A2_lanes_1234_sorted_md_brecal_tcov.bw`
<img width="1434" alt="Screenshot 2020-02-11 at 12 21 38" src="https://user-images.githubusercontent.com/584738/74232504-3afcb980-4cc9-11ea-9a12-0a5d927affda.png">
3. If I remove the "track" manually:
<img width="1434" alt="Screenshot 2020-02-11 at 12 22 48" src="https://user-images.githubusercontent.com/584738/74232585-654e7700-4cc9-11ea-99eb-6ebd59d9555b.png">

**Comment by dnil** [comment]
Ah, yes, we don't primarily intend to view the mapq track (although it is not a poor idea). Leaving it in the file will also upset chromograph, if I recall a thread with @jemten and @mikaell correctly. So this should be the file fed to chronograph,  so the one with ```-u``` to TIDDIT. Sorry, I thought I looked for that but alas.

**Comment by henrikstranneheim** [comment]
- I think I got the tiddit wig to work
- And after sorting the upd bed, those seem to work as well.
- I need to generate some data before I can test the rhocall viz wig.

@dnil Which file(s) does IGV need; only the index file i.e. (.bw, .bb); or both index and original data file i.e. (.wig & .bw, .bed & .bb)?

**Comment by dnil** [comment]
:+1: Great! It should only need the .bw - that has the data and an internal index section. And I assume by analogy the same is true for .bb, though I haven't tested. If you have a .bb at hand, you could just try loading it in a regular desktop IGV to see that it opens without the original .bed.
