### ISSUE TITLE
MT deletions?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1365]
**Is your feature request related to a problem? Please describe.**
I and Nicole couldn't find MT deletions in a case with an obvious one. I do recall @J35P312  fixing this issue in TIDDIT and and @henrikstranneheim testing it? Is it by any chance so that this is not currently in routine production? If it is, we can move this to a TIDDIT issue.. Thanks!

**Comment by henrikstranneheim** [comment]
There is nothing MT specific in the CLI call to TIDDIT in MIP today. I thought TIDDIT switched models internally when analysing the MT contig. But perhaps I am mistaken @J35P312 ?

**Comment by J35P312** [comment]
Yep, MT deletions should be found by running TIDDIT as usual.
Have you checked the unfiltered VCF file? Maybe it was picked up by some filter?
What version of tiddit is being used in production?

**Comment by henrikstranneheim** [comment]
@J35P312 The version is: 2.7.1

@dnil Could you send me the case and sample so I can look into the vcf?

**Comment by dnil** [comment]
And MT is among the analysed contigs? Good. I'll send an email..

**Comment by henrikstranneheim** [comment]
It should be as TIDDIT reads the entire vcf, but I will double check.

👍

**Comment by J35P312** [comment]
I have checked the code of version 2.7.1, and the MT calling update are present in that version. 
Hence I would guess the deletion is called, but the we only validated the MT calling on a few cases, so some hickups may be possible =P.

**Comment by henrikstranneheim** [comment]
Looks like a TIDDIT calling issue. Closing this for now
