### ISSUE TITLE
Chromograph ideo files

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1385]
**Describe the feature**
The chromograph app can produce ideograms that scout uses to display chromosome overviews. Even if these are effectively static given a set genome version and chromograph version, it  would appear easiest if MIP always makes new ones. Alternatively, CG, Scout or possibly HK would have to keep track of the chromograph and genom version used for a particular case, and merge in an appropriate version of the "static" files.

**Expected behavior**
Including a 
``` 
 --ideo <BED-filepath>
```
to produce and export ideogram pngs. 

This isn't a bug as much as an incomplete feature - feel free to change label!

**Comment by jemten** [comment]
Couldn't get the --ideo option to work. I have made an issue/asked for help on chromograph's github page [#20](https://github.com/mikaell/chromograph/issues/20)

**Comment by jemten** [comment]
fixed in release 8.2.4
