### ISSUE TITLE
gnomAD Freq. is wrong?

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/MIP#1420]
https://scout.scilifelab.se/cust002/F0033643/a7060d35cbdc665b86f2e4db7694b6f0

Why is this?
Could we have a text that states what Frequency Source (Dataset) is displayed?
"gnomADv.2.1.1 (controls)" etc.

**Comment by dnil** [comment]
(and by the way, we quite agree with the displaying annotation source versions - this now ranks as the third oldest open Scout / Solna issue - https://github.com/Clinical-Genomics/scout/issues/442)

**Comment by dnil** [comment]
By the way this particular variant is perhaps of interest to @J35P312 as it is appears associated with a processed pseudogene:

<img width="752" alt="Screenshot 2020-03-17 at 15 55 19" src="https://user-images.githubusercontent.com/758570/76869227-48790680-6868-11ea-8489-f56bc7157fd6.png">

**Comment by henrikstranneheim** [comment]
`GNOMADAF_popmax` is renamed to `GNOMAD_AF_popmax`, but the value is taken straight from the origin gnomad vcf key:
 `##INFO=<ID=AF_popmax,Number=A,Type=Float,Description="Maximum allele frequency across populations (excluding samples of Ashkenazi, Finnish, and indeterminate ancestry)">`

This particular variant has the RF:
`##FILTER=<ID=RF,Description="Failed random forest filtering thresholds of 0.2634762834546574, 0.22213813189901457 (probabilities of being a true positive variant) for SNPs, indels">`

and AC0:
`##FILTER=<ID=AC0,Description="Allele count is zero after filtering out low-confidence genotypes (GQ < 20; DP < 10; and AB < 0.2 for het calls)">`

But you can see that in the Gnomad browser and it nothing that we relay as a annotation in the raw data.

**Comment by dnil** [comment]
Confirm this is still awkward in the ref file (`grch37_gnomad_reformated_-r2.1.1-.vcf.gz`) the final VCF thinks is responsible for the annotation:
`2       179309165       rs75862065      G       A       605.85  AC0;RF  AF=0`
Are those numbers collected from the genomes version by any chance? There were only like 19k genomes in that dataset version, and none of them had the variant in question called whereas there were several in the exomes part..

**Comment by dnil** [comment]
Yep! That explains it:
`##CL=vcfsubset --keep-info=AF,AF_popmax --input=/home/henrik.stranneheim/develop/mip_references/grch37_gnomad.genomes_-r2.1.1-.vcf.gz --output=/home/henrik.stranneheim/develop/mip_references/grch37_gnomad_reformated_-r2.1.1-.vcf
.gz
`

**Comment by dnil** [comment]
So to summarise, I now believe the gnomAD reference used for annotating frequency in MIP 8 is currently v2.1.1.genomes, ie the middle column you see on gnomAD 2.1.1 (full set):
<img width="534" alt="Screenshot 2020-03-17 at 16 36 12" src="https://user-images.githubusercontent.com/758570/76873022-82004080-686d-11ea-91b6-8016c3d78be6.png">

**Comment by dnil** [comment]
- From a joint perspective, we will attempt to resolve the display of versions as in  Clinical-Genomics/scout#442.
- From Scout, we will from the next release make a clear distinction between the values 0 and "-" as in not found - see https://github.com/Clinical-Genomics/scout/pull/1802.
- I'll let @henrikstranneheim answer for MIP, but since a move to GRCh38 would effectively resolve the issue, we should probably just focus on getting there as soon and reliably as we can.

**Comment by henrikstranneheim** [comment]
Sound like a good plan.

Yes, moving to grch38 is on the whish list, however other things keep getting in the way. But we will get there eventually.
Closing this one.
