### ISSUE TITLE
CYP2D6 caller

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1509]
**Is your feature request related to a problem? Please describe.**
CYP2D6 is one of the most relevant pharmacogenomic genes, involved in drug metabolism and with clear precision medicine application. Delineating reads from the pseudogene CYP2D7 is difficult, but locus specific callers for wgs data are available, and have recently graduated into mainstream.

**Describe the solution you'd like**
Include the newly released https://github.com/Illumina/Cyrius 
See e g https://www.biorxiv.org/content/10.1101/2020.05.05.077966v1.

**Comment by jemten** [comment]
MIP produces a .tsv file with predicted CYP2D6 genotype for each sample.
Will be included in the next release of MIP
