### ISSUE TITLE
Newish problematic assembly quality tracks from UCSC

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1515]
**Is your feature request related to a problem? Please describe.**

UCSC now provide a new set of problematic regions in hg19. This complements previous mappability and segmental duplication regions. It would be nifty if we could annotate accordingly and display further warnings on problematic regions.

http://www.genome.ucsc.edu/cgi-bin/hgTrackUi?db=hg19&g=problematic

**Comment by henrikstranneheim** [comment]
Could be added to https://github.com/nf-core/raredisease when the time comes
