### ISSUE TITLE
Exome CNVs 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1517]
**Is your feature request related to a problem? Please describe.**
Exome CNV calling is not great, but with a decent set of references, 3+ exon CNVs can be fairly confidently called. Some of the "budget" analyses currently encompass only exomes, and it is unnccesary to miss entire gene deletions or gross region deletions on these.

**Describe the solution you'd like**
Include an exome CNV caller on the exome track, e.g. Canvas. Calibrate with normal cases for each capture_kit/platform separately (at least the latest and greatest workhorse e.g. TWIST).

**Comment by henrikstranneheim** [comment]
Sound good! We have been pondering to implement this for some time. Is it Canvas you would prefer or cnvkit or some other caller?

**Comment by dnil** [comment]
Many possibilities: I stopped evaluating these somewhere around XHMM. GATK4 CNV might be an option? I would personally not fight with R-including packages like CNVkit, but that's just me.

**Comment by J35P312** [comment]
Howdy!
This sounds like exciting stuff!
I tested Canvas a while ago. It is written in C# and requires Dotnet, but I did get it to run in a singularity container.

It had fairly low detection rate (compared to cnvnator), and required a Strelka snv vcf as input, hence I was not very happy with Canvas.

**Comment by henrikstranneheim** [comment]
Let's revisit this in https://github.com/nf-core/raredisease
