### ISSUE TITLE
Variant dup not displayed as CLINSIG in Scout

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/MIP#1625]
https://scout.scilifelab.se/cust002/F0035532/419b8a3817e8c9555dadd7e3fc3768bc

**Comment by dnil** [comment]
Compare https://www.ncbi.nlm.nih.gov/clinvar/variation/42693/ or https://varsome.com/variant/hg19/NM_000256%3Ac.3192dup.

**Comment by jemten** [comment]
Hmm, I've been digging around a bit and i can't find this variant in the clinvar vcf's older than 2020-05-06. Though from [https://www.ncbi.nlm.nih.gov/clinvar/variation/42693/](https://www.ncbi.nlm.nih.gov/clinvar/variation/42693/),it doesn't look like a particularly new addition.
In production we currently use the clinvar vcf dated 2019-10-13 but we're in the process of updating MIP and will then also update our clinvar references which will include this variant.

**Comment by dnil** [comment]
And we do find other ClinVar indels upon checking, so at least not a super-general issue. Let's call it an omission or error from ClinVar for now, and note that it will be amended soonish?

**Comment by jemten** [comment]
yeah I think that @henrikstranneheim is running the validation samples as we speak
