### ISSUE TITLE
SVs with high local count

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1628]
**Synopsis:** Many of the rather few variants that are now left on the SV lists upon loading to Scout have a very high number of local observations as per loqusDB. One explanation is that the dump we have is great, but old. Let's try dumping a new one once, and then re-evaluate.

**Suggested action:** Dump SVs when there is an opportunity, e g when a new version of MIP is about to be validated?

**Comment by henrikstranneheim** [comment]
Instructions have been added to the MIP validation template. Resolved!
