### ISSUE TITLE
MIP run without SLURM 

### ISSUE THREAD

**Issue by vipints** [Clinical-Genomics/MIP#1660]
May be it is already addressed, Sorry I didn't see in the issues. If there is already existing thread please suggest the same. 
I would like to run MIP rd_dna pipeline on a machine which doesn't have slurm installed. Can I use any specific option to perform the local computing with MIP run? 
Thanks in advance!

**Comment by vipints** [comment]
Can I connect to a job scheduler other than SLURM? my HPC in configured with a different scheduler (LSF).

**Comment by henrikstranneheim** [comment]
Unfortunately, not! So far we are only supporting SLURM. I am sorry to say that currently, we are not developping to support more job schedulers than SLURM.

**Comment by vipints** [comment]
Ok understood. No problem. This means that if I don't have a SLURM installation I can't do local compute as well right? Did I get it correct. (SLURM seems to be a requirement for MIP I guess)

**Comment by vipints** [comment]
Now I am moving the MIP computation to a different HPC where I got a tenant zone which is not having any scheduler, I have a huge machine with multiple cores. so my question is do I need a SLURM installation on this machine?

**Comment by henrikstranneheim** [comment]
Yes, I believe so. MIP always relies on SLURM to manage the DAG. However, you can run tests and dry-run, but not processes real samples without SLURM.

We are investigating adding SLURM within a mip container so be able to ship them togheter but it is not a priority for us.

**Comment by vipints** [comment]
Ok thanks @henrikstranneheim for the information.
