### ISSUE TITLE
CADD score not displayed

### ISSUE THREAD

**Issue by 47KW** [Clinical-Genomics/MIP#1689]
Hi, CADD score for missense etc are not displayed AND scores for other variants are given with many decimals.

https://scout.scilifelab.se/cust002/F0036238/variants

**Comment by dnil** [comment]
(This was WES, but looks the same for e.g. WGS test cases..)

**Comment by jemten** [comment]
Sounds bad. I'll take a look

**Comment by jemten** [comment]
This should be fixed now. Turned out that the file with the pre-calculated CADD wasn't correctly formatted. MIP analyses that starts today and onwards should get snv cadd values. We will dig into how this has affected the variant ranking in that has already been processed with mip9
