### ISSUE TITLE
Relax the constraints on fastq filen name and header for external fastq files

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#1698]
External fastq files often comes with truncated file names and/or headers. This causes delays and a lot of manual reformatting for the production team. 
Proposed solution: Introduce a new flag that changes the requirements of the file name and header format to be as minimal as possible.

**Comment by jemten** [comment]
This issue was opened after a discussion with @henningonsbring, @emmser

**Comment by henrikstranneheim** [comment]
We will not do this in MIP.
