### ISSUE TITLE
Yaml file for Trailblazer

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/MIP#1699]
**Is your feature request related to a problem? Please describe.**
In order to track cases from any pipeline with trailblazer, we need a sacct file in a unified format and location that is the same for all pipelines

**Describe the solution you'd like**
MIP workflow should create a yaml file in pre-defined location (preferably somewhere obvious like rare-disease/cases/keenviper/slurm_jobs.yaml). The path to the file should be declared either in case config or in cg constants if it can be generalized. The file should be overwritten if the run is restarted from scratch, or  updated if re-started at intermediate step. 

**Expected output for the feature**

Format of yaml file with jobs:
```
---
justhusky:
  - '686841'
  - '686842'
  - '686843'
  - '686844'
  - '686845'
  - '686846'
  - '686847'
  - '686848'
  - '686849'
  - '686850'
  - '686851'
  - '686852'
```

MIP already generates such file. The request mainly concerns changing naming convention and file path to be more general and easy to work with

**Comment by henrikstranneheim** [comment]
@Mropat Sounds good! But could we place this one dir down in cases/<case_id>/analysis/slurm_jobs.yaml? The motivation for this is that this file is specific for each analysis run. Usual procedure is to always wipe the entire analysis dir and having it one step up would leave an unwanted trail of the analysis. Would that be ok?

**Comment by Mropat** [comment]
Sounds good!

**Comment by moonso** [comment]
How does trailblazer know where to look for this file @Mropat ?
