### ISSUE TITLE
Post-processing of MIP deliverable format

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#1709]
Create a tool that can read the deliverable format from the case-id_deliverables.yaml file (or possibly the qc_sample_info file).
This is especially relevant for chromograph. By default chromograph will create upd images for the chromosomes containing upd:s. Before we have called upd:s there are no way of knowing what files chromograph will create. Right now, chromograph are producing empty files for the chromosomes lacking upd:s. A neater solution would be a separate program that is executed in the end and checks what files are actually created.

**Comment by henrikstranneheim** [comment]
We will not implement this.
