### ISSUE TITLE
Consider changing from MEAN_TARGET_COVERAGE to MEDIAN_TARGET_COVERAGE for exome/panels

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/MIP#1719]
**Describe the bug**
MIP threshold considers MEAN_TARGET_COVERAGE, however for a poor quality sample MEAN_TARGET_COVERAGE may be deviating a lot from MEDIAN_TARGET_COVERAGE. 

MEDIAN_TARGET_COVERAGE is a much better measurement for covarage for poor quality samples. It also works well for good quality samples (not deviating much between MEAN_TARGET_COVERAGE and MEDIAN_TARGET_COVERAGE).

Therefore, considering changing from MEAN_TARGET_COVERAGE to MEDIAN_TARGET_COVERAGE in MIP.

The phenomenon has been observed for multiple samples/projects in BALSAMIC analysis.

**Comment by vwirta** [comment]
Good suggestion! We have noticed a big difference for low quality samples, where the MEAN is not describing the true quality of the analysis.

**Comment by jemten** [comment]
Sounds good!
Is this mainly a problem with exomes or does this affect genomes as well?

**Comment by annaengstrom** [comment]
I would say TGA samples, @vwirta agreed?

**Comment by vwirta** [comment]
Tga and wes

**Comment by annaengstrom** [comment]
> Tga and wes
> […](#)


I always though TGA = panel and wes ;)

**Comment by jemten** [comment]
@annaengstrom, The changes has been merged to develop and will be a part of the next release of MIP

**Comment by jemten** [comment]
done as of mip v9.1.2
