### ISSUE TITLE
Question on MIP analyse rd_dna_panel with data

### ISSUE THREAD

**Issue by vipints** [Clinical-Genomics/MIP#1735]
Dear MIP team, 
We are trying to perform an analysis with MIP using the following command: 
```
/data/apps/MIP/MIP_v9.0.0/mip analyse rd_dna_panel --config_file ../mip_rd_dna_panel_config.yaml test_samples --cluster_constant_path /data/analysis_testdata_20200901 --reference_dir /data/apps/MIP/mip_references/ --exome_target_bed IAA20691.bed=TestN --verbose --outscript_dir outscripts/ --outdata_dir outdata/
```
on a slurm based platform. The above command run properly and was able to dispatch the jobs properly something like this in the stdout
```
INFO] 2020/10/27 15:34:45 MIP_ANALYSE - Sbatch script submitted, job id: 508
[INFO] 2020/10/27 15:34:45 MIP_ANALYSE - To check status of job, please run 'squeue -j 508'
[INFO] 2020/10/27 15:34:45 MIP_ANALYSE - To cancel job, please run 'scancel 508'
[INFO] 2020/10/27 15:34:45 MIP_ANALYSE - Wrote: /data/analysis_testdata_20200901/test_samples/analysis/test_samples_qc_sample_info.yaml
[INFO] 2020/10/27 15:34:45 MIP_ANALYSE - Wrote: /data/analysis_testdata_20200901/test_samples/test_wf/outdata/mip_log/2020-10-27/slurm_job_ids_2020-10-27T15:34:36.yaml
[INFO] 2020/10/27 15:34:45 MIP_ANALYSE - Wrote: /data/analysis_testdata_20200901/test_samples/test_wf/outdata/test_samples_deliverables.yaml
```
Now on the cluster platform I can see the jobs are in the pending state. 
```
JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
457     batch vcfanno_    vipin PD       0:00     18 (PartitionConfig)
458     batch vcfanno_    vipin PD       0:00     18 (PartitionConfig)
459     batch fastqc_a    vipin PD       0:00      1 (DependencyNeverSatisfied)
460     batch bwa_mem_    vipin PD       0:00      6 (DependencyNeverSatisfied)
...
```
When I closely looked at the job for example, 457 `JobName=vcfanno_preops_test_samples` I can see that it requested for the resources 
```
   NumNodes=18 NumCPUs=36 NumTasks=36 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=36,mem=180G,node=1,billing=36
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=1 MinMemoryNode=180G MinTmpDiskNode
```
or I misunderstood something (sorry for my ignorance, I m very new to the job manager slurm). Do you think this particular task requires this much of resource to continue. I think the rest of the jobs are dependent on the first job and then only I can release the other jobs to execute on the platform. 
Can you please comment on this? Thanks in advance and if you need any additional information, please let me know here.

**Comment by henrikstranneheim** [comment]
How many CPUs and how much RAM does each node in your cluster have? 
I do not know if the `(DependencyNeverSatisfied)` or `(PartitionConfig)` is due to this being set by the default template (which is defaulting to our cluster)?
You can set these parameters according to your specifications  in the your MIP config using these keys
`max_cores_per_node: [YOUR_NODE_CPUS]`
`node_ram_memory: [YOUR_NODE_RAM]`

MIP will create a dependency tree when submitting to SLURM and then let SLURM execute jobs as they are completed. It should look something like this:
<img width="1256" alt="Screenshot 2020-12-01 at 13 27 44" src="https://user-images.githubusercontent.com/584738/100740513-2238ce00-33d9-11eb-993d-a0cd090d2e8d.png">

where the last column is your NODELIST(REASON). 

This what it looks like for a bwa_mem job (i just picked one):
`   Partition=core AllocNode:Sid=hasta:196969
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=compute-0-23
   BatchHost=compute-0-23
   NumNodes=1 NumCPUs=36 NumTasks=36 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=36,mem=180G,node=1,billing=36
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
     Nodes=compute-0-23 CPU_IDs=0-35 Mem=184320 GRES_IDX=
   MinCPUsNode=36 MinMemoryNode=180G MinTmpDiskNode=0`

**Comment by vipints** [comment]
Hi @henrikstranneheim, thanks for the tips! I have a compute node with 16 cores and 64 memory machine. 
I have modified my config file with the cores and memory and started running the command: 
```
/data/apps/MIP/MIP_v9.0.0/mip analyse rd_dna_panel --config_file ../mip_rd_dna_panel_config.yaml test_samples --cluster_constant_path /data/analysis_testdata_20200901 --reference_dir /data/apps/MIP/mip_references/ --exome_target_bed IAA20691.bed=TestN --verbose --outscript_dir outscripts/ --outdata_dir outdata/
```
From the STDOUT info I can see the cores and memory set according to the config file. Now I see following Warning messages: 
```
[WARN] 2020/12/01 14:35:41 MIP_ANALYSE - Will try to create required /data/apps/MIP/mip_references/IAA20691.bed associated file(s) before executing picardtools_collecthsmetrics
[INFO] 2020/12/01 14:35:41 MIP_ANALYSE - Sbatch script submitted, job id: 689
...
[WARN] 2020/12/01 14:35:43 MIP_ANALYSE - 	Cannot detect that vt_normalize has processed reference: /data/apps/MIP/mip_references/grch37_gnomad_reformated_-r2.1.1-.vcf.gz
[WARN] 2020/12/01 14:35:44 MIP_ANALYSE - 	Cannot detect that vt_decompose has processed reference: /data/apps/MIP/mip_references/grch37_gnomad_reformated_-r2.1.1-.vcf.gz
```
and later program terminates with the following STDOUT: 
```
[INFO] 2020/12/01 14:35:46 MIP_ANALYSE - Creating sbatch script for vcfanno_preops and writing script file(s) to: /data/analysis_testdata_20200901/test_samples/test_wf/outscripts/test_samples/vcfanno_preops/vcfanno_preops_test_samples.5.sh
[INFO] 2020/12/01 14:35:46 MIP_ANALYSE - Sbatch script vcfanno_preops data files will be written to: /data/analysis_testdata_20200901/test_samples/test_wf/outdata/test_samples/vcfanno_preops
Use of uninitialized value in join or string at /data/apps/MIP/MIP_v9.0.0/lib/MIP/Program/Gnu/Coreutils.pm line 106.
Use of uninitialized value in join or string at /data/apps/MIP/MIP_v9.0.0/lib/MIP/Program/Gnu/Coreutils.pm line 106.
Use of uninitialized value in join or string at /data/apps/MIP/MIP_v9.0.0/lib/MIP/Program/Gnu/Coreutils.pm line 106.
Use of uninitialized value in join or string at /data/apps/MIP/MIP_v9.0.0/lib/MIP/Program/Gnu/Coreutils.pm line 106.
Key 'infile_path' must be defined when passed at /data/apps/MIP/MIP_v9.0.0/lib/MIP/Recipes/Analysis/Variant_annotation.pm line 867.
Could not parse arguments! at /data/apps/MIP/MIP_v9.0.0/lib/MIP/Recipes/Analysis/Variant_annotation.pm line 867.
```
Can you see any reason for such a failing status? Thanks!

**Comment by vipints** [comment]
In order to run `mip analyse rd_dna_panel` pipeline any idea about a rough estimate of resources required?

**Comment by jemten** [comment]
Hi @vipints, 
I'll look into this. Some tweaking might be required to make it run with the resources you have available

**Comment by jemten** [comment]
Which version of MIP are you running? There were some issues with vcfanno_preops in verion 9.0.0 so we removed it in 9.0.3.

**Comment by vipints** [comment]
I am running with MIP_v9.0.0, may be then I need to upgrade to MIP_v9.0.3

**Comment by jemten** [comment]
I would try that first. Or rather go to the latest one which is MIP v9.0.6

It still might be that you have discovered a bug. Don't hesitate to get back if the issue persists or you are running into more issues with MIP.

**Comment by henrikstranneheim** [comment]
It you are only updating MIP and not its dependencies you only have to run pull the latest master in your local git repo and then run:
```
perl mip install --environment_name [YOUR_MIP_CONDA_ENV] --select_programs mip_scripts
```

**Comment by henrikstranneheim** [comment]
@vipints How did it go?

**Comment by henrikstranneheim** [comment]
I will close this as the issue seems resolved - please reopen if you disagree
