### ISSUE TITLE
Setting Singularity cache 

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#1786]

**Comment by henrikstranneheim** [comment]
@jemten @ramprasadn Do you still experience issues with singularity pull crashing due to IO with dockerhub?

**Comment by jemten** [comment]
It's been a while since. I think the issue was mainly with programs that made multiple calls to the same image at same time.

**Comment by henrikstranneheim** [comment]
ok, closing this. Let's open another more specific issue if the needs arise
