### ISSUE TITLE
Update programs for MIP version 10

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#1788]
**Tools**
- [x] bwamem (no source update release)
- [x] bwa-mem2 - AJ
- [x] cnvnator (no source update release)
- [x] cyrius
- [x] expansionhunter (no source update release)
- [x] fastqc (no source update release)
- [x] [GATK](https://github.com/Clinical-Genomics/MIP/pull/1861)
- [x] [htslib](https://github.com/Clinical-Genomics/MIP/pull/1821)
- [x] manta (no source update release)
- [x] [picard](https://github.com/Clinical-Genomics/MIP/pull/1825)
- [x] [sambamba](https://github.com/Clinical-Genomics/MIP/pull/1833)
- [x] [smncopynumbercaller](https://github.com/Clinical-Genomics/MIP/pull/1840)
- [x] star - AJ
- [x] star-fusion - RN
- [x] arriba -AJ
- [x] salmon - AJ
- [x] [svdb](https://github.com/Clinical-Genomics/MIP/pull/1858)
- [x] [telomerecat](https://github.com/Clinical-Genomics/MIP/pull/1855) (HS; fails willl let it sit for a while and we migth skip updating )
- [x] [tiddit](https://github.com/Clinical-Genomics/MIP/pull/1831)
- [x] vcfanno (no source update release)
- [x] vcf2cytosure (no source update release)
- [x] [VEP](https://github.com/Clinical-Genomics/MIP/pull/1863)

**Comment by jemten** [comment]
I think this is done. Providing nothing new has been released in the last few day
