### ISSUE TITLE
mip generating HSmetrics results for WGS, is this intentional?

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/MIP#1834]
HSMetrics results from Picardtools are aimed for target-capture assays, yet mip generates this for wgs appllications. Is this intentional?

fyi, I'll omit mip's hsmetrics for wgs applications temporarily from Vogue end point so Vogue's DB can stay clean.

**Comment by henrikstranneheim** [comment]
yeah, we are using this a bit sloppily to assay "exome" parts of the WGS analysis to get common metrics between the 2 assays even though some metrics do not make any sense. I guess you can just exclude the WGS ones based on apptag in cg.

**Comment by hassanfa** [comment]
Alright, I'll exclude it temporarily until we find the best way to utilize this information. Raw data in vogue will not be affected, just processed front end will be cleaned up. i am doing same for balsamic data.
