### ISSUE TITLE
MIP outfiles required for igv.js splice junctions track

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/MIP#1846]
I've been checking the documentation of igv.js regarding the [splice junction track](https://github.com/igvteam/igv.js/wiki/Splice-Junctions).

It is a track of type `merged`, which means is composed of two tracks:
- a **bigWig** file created from the bam/cram file (with bam2coverage or whichever software we have already in the pipeline)
- An indexed junctions **.bed.gz** file created from from some columns (chrom, start, end, label, spanning-read-count, strand columns) of the start aligner SJ.out.tab outfile. Oneliner for creating it: 
```
gunzip -c mysample.SJ.out.tab.gz | awk -v OFS='\t' '{ if($7 > 0) { print }}' | awk -v OFS='\t' '{ print $1, $2 - 1, $3, $7 + $8, $7, (($4 != 2) ? "+" : "-") }' | bgzip > mysample.SJ.out.bed.gz
tabix mysample.SJ.out.bed.gz

```
What do we have already available as output files from the pipeline and what should be done?

**Comment by jemten** [comment]
We produce the SAMPLE.SJ.out.tab already but no bigwig file. I could add a process to the pipeline to produce the bigWig and the bed file. Whatever is easiest :)

**Comment by northwestwitch** [comment]
I think the easiest would be to create them as additional outfiles from the pipeline. And then we need cg to write the path to both on each sample of the scout config file.

**Comment by jemten** [comment]
Sounds good! I'll add it to the pipeline

**Comment by northwestwitch** [comment]
I have no idea. I've checked in the igv.js repo and it looks like they can parse both, so I'd go for the most common format, variableStep?

**Comment by jemten** [comment]
Thanks for quick response 🚀 
I'll just go ahead with the default then - think it's variableStep. I can change it later if necessary 😄

**Comment by jemten** [comment]
done
