### ISSUE TITLE
MIP failed to install some program

### ISSUE THREAD

**Issue by BiMo88** [Clinical-Genomics/MIP#1851]
Dear all, 
I've installed MIP version 9.1.3 on a UBUNTU 20.04 LTS desktop but when I launch mip.sh I have this messages:

_2021-03-24 14:44:18 (254 KB/s) - ‘/home/bioinfo/Programs/MIP/mip_references/ensembl-tools-release-100/cache/Plugins/fordownload.tar.gz’ saved [1505157/1505157]

INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached image
WARNING: integrity: signature not found for object group 1
WARNING: Skipping container verification
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image
INFO:    Using cached SIF image

and the test reports that mip failed to install 2 programs:

	Testing installation

ok 1 - Can execute: arriba
ok 2 - Can execute: bedtools
ok 3 - Can execute: blobfish
ok 4 - Can execute: bootstrapann
ok 5 - Program in path: bwa
ok 6 - Program in path: bwa-mem2
ok 7 - Program in path: bwakit
not ok 8 - Can execute: cadd
#   Failed test 'Can execute: cadd'
#   at -e line 1.
ok 9 - Can execute: chanjo
ok 10 - Can execute: chromograph
ok 11 - Program in path: cnvnator
ok 12 - Can execute: cyrius
ok 13 - Can execute: delly
ok 14 - Can execute: expansionhunter
ok 15 - Can execute: fastqc
ok 16 - Can execute: gatk
ok 17 - Can execute: gatk4
ok 18 - Can execute: genmod
ok 19 - Can execute: gffcompare
ok 20 - Can execute: htslib
ok 21 - Can execute: manta
ok 22 - Can execute: mip_scripts
not ok 23 - Can execute: multiqc
#   Failed test 'Can execute: multiqc'
#   at -e line 1.
ok 24 - Can execute: peddy
ok 25 - Program in path: picard
ok 26 - Can execute: plink
ok 27 - Can execute: preseq
ok 28 - Program in path: rhocall
ok 29 - Program in path: rseqc
ok 30 - Can execute: rtg-tools
ok 31 - Can execute: salmon
ok 32 - Can execute: sambamba
ok 33 - Can execute: star
ok 34 - Can execute: star-fusion
ok 35 - Can execute: stranger
ok 36 - Can execute: stringtie
ok 37 - Can execute: svdb
ok 38 - Can execute: telomerecat
ok 39 - Can execute: tiddit
ok 40 - Can execute: trim-galore
ok 41 - Can execute: upd
ok 42 - Can execute: varg
ok 43 - Can execute: variant_integrity
ok 44 - Can execute: vcf2cytosure
ok 45 - Can execute: vcfanno
ok 46 - Can execute: vep
ok 47 - Can execute: vt
1..47
# Looks like you failed 2 tests of 47.

	MIP failed to install some programs in: mip
 
and I don't know why.
My computer specs:

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          72
On-line CPU(s) list:             0-71
Thread(s) per core:              2
Core(s) per socket:              18
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz

**Comment by jemten** [comment]
Hi there @BiMo88 ,
Nice to see that you want to try out MIP 😃  
We will be releasing a new version of MIP in the next few weeks and one of the big updates is the installation process and how programs are executed. You think you could wait until the release and then give it another shot? If you're eager you can checkout the develop branch and try it out already. The main thing that we need to do before releasing is to update the last programs and references and validate the results against our test set.

We're also about to start porting the pipeline to nextflow in order to make it more portable but it will take some time before that process is complete. 

cheers,
Anders

**Comment by BiMo88** [comment]
Hi @jemten,
Thank you for the fast answer. In this case I look forward to the new version of MIP :)

Matteo
