### ISSUE TITLE
New loqus db dump for SV

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1859]
Time flies, and cases abound! We note a few structural variants that reappear and have accrued a count in loqus but are not yet in the dump set. A new dump would be appreciated to speed up case analysis! Cheers!

**Comment by jemten** [comment]
Yeah, time flies indeed. We make a dump for each release of MIP, but as per usual that took much longer than expected. The current plan is to release a new MIP version in the week after the schools have had their easter holidays 🐣

**Comment by jemten** [comment]
MIP has been update and with it we have a new locus dump. Closing this
