### ISSUE TITLE
Annotate MITOMAP associated diseases in VCFs

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/MIP#1870]
Our collaborators from Lund have added a nice new feature in Scout: the possibility to parse and save a VCF INFO field that describes the MT-associated diseases (name of the field is `MitomapAssociatedDiseases`). 

The annotation is done using [HmtNote](https://github.com/robertopreste/HmtNote), that in turn pulls info from [HmtVar](https://www.hmtvar.uniba.it/).

It's not urgent, but it might be a nice new feature for when you have time! :)

**Comment by henrikstranneheim** [comment]
Done
