### ISSUE TITLE
Stranger update and corresponding references update

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1913]
[Stranger v0.8.0](https://github.com/moonso/stranger/tree/v0.8.0) is out. A bugfix and a lot of mostly small but annoying reference updates. We will likely see more of the latter ones as we check more loci with REViewer. Also some integrity checks and fixes between hg19 and hg38 that will not directly affect production yet, but good to have in place. Sorry about the timing, but perhaps it is just as well.

I guess I will PR the small references repo as well as usual. 😬

**Comment by jemten** [comment]
Not too bad of a timing. We will probably patch MIP 10 next week as we find some small bugs. Will try to include this in that update. And yes a PR to the reference repo would be great.

**Comment by jemten** [comment]
@dnil Are you planning to update the stranger version thats on pypi to v0.8.0?

**Comment by dnil** [comment]
😬 I forgot we don't do that automagically. I'll fix it, and run a quick test on hasta with v4.0.2 as well in the process.

**Comment by dnil** [comment]
Thank you for the reminder! v0.8.0 should be on PyPi now, and for what it is worth at least runs ok on hasta with a recent MIP10 case.

**Comment by dnil** [comment]
There is also a PR here https://github.com/Clinical-Genomics/reference-files/pull/45.
