### ISSUE TITLE
Same variant - but not the same score - WHY???

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/MIP#1928]
https://scout.scilifelab.se/cust002/F0036387/3c06a1afb834a5b71f69d67c1e8279bc

https://scout.scilifelab.se/cust002/F0036997/9f6ac8b7e045176c1e91c3d4580d4b1d

If we add up it turns to 34 - but in one of the it adds up to 28...
Same numbers...
![image](https://user-images.githubusercontent.com/17139607/128175913-bf9b5030-023e-4cc9-b2c7-76d368373a35.png)

**Comment by jemten** [comment]
Good catch @KickiLagerstedt! We'll look into it

**Comment by henrikstranneheim** [comment]
I think we have a penalty of 6 related to bad compound pairs. I do not remember exactly how it is supposed to behave and I will not be back until next week. It should be part of the Genmod compounds command if anyone has time to look it up

**Comment by jemten** [comment]
You're right @henrikstranneheim. The two compound variants of have rankscore of -3 and genmod gives a -6 penalty to the the other variants in the pair. The threshold for what is a low score is set to 9 and below.

**Comment by dnil** [comment]
Good catch indeed! Here: https://github.com/moonso/genmod/blob/d997a845f0bee142fc53d9a0a5595e4907718c8a/genmod/score_variants/compound_scorer.py#L155

I couldn't find it in the docs, it is statically written into the code independent of the rank model version and seems more appropriate for trios and possibly for older iterations where compound rank also was additive? At least in this particular situation, it seems unclear why the variant should receive a lower score when other (be that normal or noise) variants are present in the gene?
