### ISSUE TITLE
mtDNA variants missing in Scout

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/MIP#1944]
I have today noticed that mtDNA variants unfortunately are missing in Scout and in the mtDNA report again.

I was analyzing a case in which I earlier have sequenced mtDNA by sanger sequencing. According to this there are 11 variants (8 in genes and 3 in the control region) missing in Scout and in the mtDNA report. I have checked IGV data and they are showing up as homoplasmic variants there. For mtDNA we have decided all variants  should be presented in the mtDNA report and all variants in genes should be presented in the gene panel "Mitochondrial DNA".

My guess is that they have been filtered out because of their high frequency but this is not supposed to happen for the mtDNA variants.

The specific case I noticed this in is 20258 and the missing variants are:
m.73a>g | control region
m.263a>g | control region
m.1438a>g | MT-RNR1
m.2706a>g | MR-RNR2
m.4769a>g | MT-ND2
m.7028c>t | MT-CO1
m.8860a>g | MT-ATP6
m.11719g>a | MT-ND4
m.14766c>t | MT-CYB
m.15326a>g | MT-CYB
m.16519t>c | control region

Could you please check what has happened and could you please try to find out when this happened. This case is from 
2021-01-26. Is it still like this? Since how long have variants been filtered out like this?

**Comment by henrikstranneheim** [comment]
There is a general frequency filtering being done on the VCF
```
# From Swegen
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
MT	73	rs3087742	A	G	6.00613e+06	VQSRTrancheSNP99.90to100.00	AC=1098;AF=0.549

# From loqusDB
MT	1438	.	A	G	.	.	Obs=2452;Hom=2449;Frq=0.56786
```
If I remember correctly we filter out anything above 0.40.

If you still want to keep these very common ones we have to purge the Swegen/Gnomad data from all Mitochondrial variants or exclude it from filtering.

**Comment by 1ctw** [comment]
From what we have decided earlier this general frequency filtering should not affect mtDNA variants. 

I don´t know how you solved this earlier but I guess you have excluded mtDNA from this filtering? Last time we had this discussion was in October 2018 and then you got it to work well:) The question is when you started to filter them again?

**Comment by jemten** [comment]
OK, we'll make a hotfix for this so that all mt variants are kept regardless of their population frequency. Will also investigate for how long they've been filtered.

**Comment by jemten** [comment]
OK. so from what I've found out we've been filtering out common mitochondrial (above 0.4) for quite a long time, at least a year if not longer. We will implement a hotfix in MIP this week so that the variants are kept in the vcf.

**Comment by jemten** [comment]
@1ctw, a hotfix has been deployed so I'm closing this issue. Feel free to reopen or write a new one if you run into more issues
