### ISSUE TITLE
Cases passed according to atlas should not fail, median/mean target coverage

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/MIP#1948]
**Is your feature request related to a problem? Please describe.**
Right now it is not explicitly stated on atlas if the threshold is 26x mean or median target coverage to pass a MIP-analysis with a C030 app tag. Case richcougar failed on "FAILED:collecthsmetrics_MEDIAN_TARGET_COVERAGE:24" (see `/home/proj/production/rare-disease/cases/richcougar/analysis/richcougar/qccollect_ar/richcougar_qc_metrics.yaml`). Meanwhile the same case reached 26.15x "Medelsekvensdjup" when checking the scout report.

According to my interpretation, based on the atlas documentation for MIP, this case should be passed, but it failed on the analysisrunstatus step.

**Describe the solution you'd like**
Consider if we should use mean or median target coverage. Perhaps median target coverage is better to use in scout.

**Comment by henrikstranneheim** [comment]
@jemten Did we not switch to median target coverage a while ago?

**Comment by jemten** [comment]
Yes MIP has transferred to using median as per #1746. However it looks like the scout hasn't shifted.

**Comment by jemten** [comment]
Closing this for now as it isn't really a MIP issue. Seems like the coverage criteria needs clarification. Once we have decided which criteria to implement we can reopen this.
