### ISSUE TITLE
Annotating 5'UTRs

### ISSUE THREAD

**Issue by fulyataylan** [Clinical-Genomics/MIP#1954]
Hi!

I have recently listened to an ESHG talk about annotating variants in 5'UTR. I found it very interesting and it is worth trying. Below you can find their GitHub page and publications.

[https://github.com/ImperialCardioGenetics/UTRannotator](https://github.com/ImperialCardioGenetics/UTRannotator)

**About the role of 5'UTR variants in human genetic disease:**

Whiffin, N., Karczewski, K.J., Zhang, X. et al. Characterising the loss-of-function impact of 5’ untranslated region variants in 15,708 individuals. Nat Commun 11, 2523 (2020). https://doi.org/10.1038/s41467-019-10717-9

**About UTRannotator:**

Annotating high-impact 5'untranslated region variants with the UTRannotator Zhang, X., Wakeling, M.N., Ware, J.S, Whiffin, N. Bioinformatics; doi: https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btaa783/5905476

Kind regards,
Fulya

**Comment by henrikstranneheim** [comment]
Will not be done in MIP
