### ISSUE TITLE
Request for new bcf output file

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/MIP#1968]
**Describe the solution you'd like**
Currently Mip produces unfiltered bcf file for upload of MAF variants  to genotype and loqusdb. 
In order to speed up the upload to those applications and consume less ram doing so, it would be good to have a file for this purpose containing only the 50 maf variants. 
The file would be stored in housekeeper and retrieved for upload using a very descriptive tag.

**Comment by jemten** [comment]
Sounds sensible. We'll try to implement this in the next release.

**Comment by henrikstranneheim** [comment]
@Clinical-Genomics/rare-disease Let's discuss if we should include this together with a GENS release post MIP 11 or transfer this to https://github.com/nf-core/raredisease

**Comment by henrikstranneheim** [comment]
@Mropat What about streaming the 50 variants from the bcf into the rest-api? Would that be possible?

**Comment by Mropat** [comment]
@henrikstranneheim yes it would be possible, but the entire bcf is still going to be opened and read by a dedicated service on hasta

**Comment by henrikstranneheim** [comment]
Since the BCF is indexed it will be a tiny amount and not the entire file. So yes, a file handle will be opened but the data stream will be very small and fast

**Comment by jemten** [comment]
Closing this for now. Feel free to reopen if you think we should revisit
