### ISSUE TITLE
Request for MIP to produce d4 file for chanjo upload

### ISSUE THREAD

**Issue by Mropat** [Clinical-Genomics/MIP#1969]
[We already have a fork of d4tools and a container build](https://github.com/Clinical-Genomics/d4-format)
[As well as a dockerhub image](https://hub.docker.com/r/clinicalgenomics/d4tools)

**Comment by henrikstranneheim** [comment]
This has been added to [nf-core/raredisease](https://github.com/nf-core/raredisease) by @ramprasadn. We will focus on getting that pipeline ready for production and not to develop MIP further.
