### ISSUE TITLE
WES SVs default to "all callers" - MIP tag interaction issue?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1977]
All randomly drawn WES SV vars look like they were called by all callers. I would assume they are rather not tagged properly, and this is a default?

![Screenshot 2022-03-03 at 16 48 49](https://user-images.githubusercontent.com/758570/156600479-9533a8c6-3f4b-4931-8b52-f2250c951379.png)

**Comment by jemten** [comment]
@dnil Do you want to use the tag `set` for SV's? For SNV/INDELs we have the `FOUND_IN` tag.

**Comment by dnil** [comment]
I would prefer the FOUND_IN tags! If that is already enabled also for SV WES singletons in MIP 11 we're good to go!

**Comment by jemten** [comment]
We'll have to add it for MIP 11. There might be a bit of complexity as the `set` tag comes from SVDB and when we run with multiple callers we would need process that tag to see which callers that made the call. Alternatively, I've just heard from @J35P312 that the cancer team is working on having SVDB to just add the INFO field of all callers to the merged call. Then Scout would have to parse that for the `FOUND_IN` tags. We'll see where we end up :)

**Comment by dnil** [comment]
Worst case could also use a fallback similar to the SNVs with GATK only, removing the `set=Intersection` when there is only one caller. Either was should work - just let us know and we'll update accordingly!
