### ISSUE TITLE
REVEL rankscores are annotated instead of REVEL scores

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1981]
**Describe the bug**
This is borderline between a bug and a feature. REVEL rankscores are somewhat correlated to the scores fortunately, but threshold values indicate both genmod and the downstream scout users treat them as scores rather than rankscores. 

**To Reproduce**
Notice that `REVEL_rankscore` is annotated on coding variants from coding sequence, rather than `REVEL_score`.

**Expected behavior**
At least `REVEL_score`, or both it and `REVEL_rankscore` for a transition period, should be annotated. 

The `REVEL_score` is present as a column in the `dbNSFP` reference files, and can be annotated by giving `REVEL_score` as an option to the `VEP` `dbNSFP` plugin, e.g. like here https://github.com/Clinical-Genomics/MIP/blob/af1965287118c94f79f0944d80a68dbb0e331c5f/templates/mip_rd_dna_vcf_rerun_config.yaml#L88

**Additional context**
The native scores from REVEL have started appearing in some guidelines, especially for cancer (https://academic.oup.com/clinchem/article/67/3/518/6024902). While I personally feel this is rather naive and bioinformatics ignorant (they probably have not locked down the REVEL or transcript set version etc), it feels uneasy to supply the rankscore knowing it could differ from the native score.

**Comment by dnil** [comment]
Just checking; did you want to include this now @jemten? Scout is in principle ok either way, so anytime is good. But it could be in a patch release as well, no rush!

**Comment by jemten** [comment]
Has been implemented since mip 11.1
