### ISSUE TITLE
Tagging ExHu files for export to HK and Scout reviewer service 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1982]
**Is your feature request related to a problem? Please describe.**
Expansion Hunter generates some files that Scout Reviewer Service would need to generate images for Scout.
See https://github.com/Clinical-Genomics/project-planning/issues/361 for details.

Basically, sorted and indexed graph realignment bam-lets plus individual level ExHu output VCFs should do the trick. The sorting and indexing may not be done currently, so another set of samtools calls may be needed?

We still want the Stranger annotated, family VCFs for Scout though, so this is only a request to add file tagging, not change any current ones.

We don't have keys for this yet, so naming is free, but maybe something like `EXHU_BAMLET` and `EXHU_IND_VCF` on the sample/individual level.

The individual VCFs could potentially be recovered by splitting the family VCFs, but some filelds are somewhat convoluted so unless there are reasons against it, it would be easier just to run with the originals.

**Comment by jemten** [comment]
@dnil, Do we need to rename the sample in the VCF from the internal clinical genomics ID to the customer ID or can reviewer handle this?

**Comment by dnil** [comment]
@jemten I haven't tested it now, but I don't think it would matter. Reviewer itself is rather name agnostic - it will just try to use the last column in the VCF regardless, and we never got around to handling multi individual VCFs in the reviewer service. Feeding them one at the time to the service sounds like a plan.
