### ISSUE TITLE
UPD checks also on unaffected sibs

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#1983]
**Is your feature request related to a problem? Please describe.**
Currently, unaffected siblings get no UPD calls etc from Chromograph. This could be informative to contrast with affected family members with multiple affected regions. Compare e.g. https://scout.scilifelab.se/cust004/522701400072fam-quadro - thank you @sofievonlanthen for noticing!

**Describe the solution you'd like**
It would seem possible and interesting to generate UPD tracks and corresponding pictures for all individuals with available parents in a pedigree

**Describe alternatives you've considered**
Users can in principle request a rerun, selecting more siblings as affected, but this can have detrimental effects on snv analysis.

**Comment by mikaell** [comment]
This should be possible to implement but I need to involve our pipeline experts.

**Comment by jemten** [comment]
Should be easy enough to generate these files in the pipeline. We're hoping to release MIP 11 this week, then make more frequent smaller releases with changes such as these.
