### ISSUE TITLE
Wrong MITOMAP associated disease?

### ISSUE THREAD

**Issue by 1ctw** [Clinical-Genomics/MIP#1995]
There is something wrong with the MITOMAP associated diseases in Scout. I have found several variants with a MITOMAP associated disease in Scout, where it seems not true when you enter Mitomap to check the variant.

Examples:

https://scout.scilifelab.se/cust003/22161/f2b9deeac9aa3e3381f3be5ce610d651

https://scout.scilifelab.se/cust003/22161/cfcb3004c417976365f94ef447bf5ef3

Could you please check what has happened. Thanks!

**Comment by jemten** [comment]
Thanks for reporting the issue. I'm on holiday right now but will take a look early next week.

**Comment by northwestwitch** [comment]
> Do you know if Lund have the same issues @northwestwitch?

I don't know. @mhkc?

**Comment by dnil** [comment]
There would also be this: https://github.com/mitoNGS/mtoolnote. It has been updated a bit more recently, but still not very active. Aside from the name being slightly offensive 😉, it also seems to derive data from hmtvar.

**Comment by ehre** [comment]
Hi,

I have no possibility to check the examples above, but it would not surprise me if an annotation source is outdated/wrong. First, if I remember the reasoning from our bioinformaticians correctly they had no way to pull data directly from MITOMAP at that time, so they used HmtNote to add (MITOMAP) annotations in Scout. I am interested in all suggestions for improvements of the mt-pipeline.

Second, when we set this up, we added links to both HmtNote/HmtVar and MITOMAP with the aim to maximise sensitivity (i.e. not dismiss any variant too quickly and have access to all information from both sources), we did note several annotations where we would not agree with either HmtVar or MITOMAP on their assessments. Particularly, it appeared that many variants were annotated as "possibly pathogenic" at a time before we had access to population data from gnomAD etc, and such a variant would now be downgraded. I hope these discrepancies will be sorted out and hopefully ClinVar will keep getting better and better.

**Comment by 1ctw** [comment]
I now have an explanation for one of the variants -> https://scout.scilifelab.se/cust003/22161/cfcb3004c417976365f94ef447bf5ef3
In Scout it is annotated m.15939CT>C but since it is a polyT-stretch it should be m.15944delT. When you manually search for that variant in Mitomap you find a connection to MELAS-MERRF. As @ehre says I would not agree with this assessment. It is a really common variant. There are lots of variants with some disease association in Mitomap and I wouldn´t agree in most of those cases. The variants with Cfrm (confirm status) in Mitomap are the ones you most probably can trust. Variants with status Reported or Conflicting reports are there on very weak grounds, but it is however good to see the links and then make your own assessment.

The other variant I have not found any explanation for. This variant is a rare variant and if there really is a disease association it would be interesting to find the source of that information.

**Comment by jemten** [comment]
So to conclude we want to keep it as is from the MIP perspective?

**Comment by jemten** [comment]
Right, closing this for now. Feel free to reopen if you feel that this warrants further discussions
