### ISSUE TITLE
Evaluate CNVKit

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#202]

**Comment by J35P312** [comment]
Aloha!
I saw you are working on adding GATK 4! How nice!
Have you read about the GATK4 CNV caller?

https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_copynumber_GermlineCNVCaller.php

I think it looks promising!

**Comment by hassanfa** [comment]
Hi!

CNVkit can also export http://cnvkit.readthedocs.io/en/latest/heterogeneity.html#estimating-tumor-purity-and-normal-contamination interval count and "SNP formatted" files used by THetA2. We should remember to add this feature to CNVkit module in case we decided to import it to MIP.

**Comment by henrikstranneheim** [comment]
Let's revisit this if requested for WES. We are almost exclusively doing WGS and have a very good SV calling already in place making this much less prioritised.
