### ISSUE TITLE
Explanation called SNV - but not seen in IGV???

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/MIP#2021]
Variant are called - but with low score, many reads per allele, not shown in IGV

https://scout.scilifelab.se/cust002/F0046529-3/23d2fc25374c8c4ee1d51012dd1ca3c7#comments

https://scout.scilifelab.se/cust002/F0046529-3/3746556ee54a7ab08acac68520632b3d

**Comment by jemten** [comment]
This is how DeepVariant see this region (https://scout.scilifelab.se/cust002/F0046529-3/23d2fc25374c8c4ee1d51012dd1ca3c7#comments) after local realignment. 
<img width="1943" alt="image" src="https://user-images.githubusercontent.com/3168925/227241477-1a8606d2-5cd8-4c94-89fb-4df772e4bb0a.png">

**Comment by jemten** [comment]
Yeah GQ=9 is a clear indicator that this is a messy region. How do you wanna proceed with this? I don't think it's very feasible to save the local realignment files for display in scout.

**Comment by dnil** [comment]
Agreed! 

I'm personally good with this explanation. The counts match the realigned variants, not the original bwa alignment. It's not a region where I would feel very confident about short read calls with respect to which repeat copy has which variant, and the quality reflects this. What do you say @KickiLagerstedt?

I definitely think we want realignment with DeepVariant, so turning it off just to simplify the view of some actually very difficult regions is hardly on the table. Is there some kind of indicator in the VCF from DeepVariant showing that it used a realignment to make this particular call, beyond the low GQ?

**Comment by jemten** [comment]
I can't see any indication of that in the VCF.  I don't think there is much we can do about this on the MIP side.

**Comment by dnil** [comment]
Ok closing this - thank you @jemten!
