### ISSUE TITLE
Normalized rank score validation

### ISSUE THREAD

**Issue by torbjorgen** [Clinical-Genomics/MIP#2055]
Run validation of MIP pipeline with new Genmod version exposing normalized rank score.

Awaiting release cycle for MIP pipeline.

**Comment by henrikstranneheim** [comment]
@torbjorgen Done?

**Comment by torbjorgen** [comment]
Still in progress, it's dependent on a new genmod version
that's being built just now.

**Comment by jemten** [comment]
done!
