### ISSUE TITLE
Relation_check not working

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/MIP#2057]
**Describe the bug**

It seems like relation_check is not performed, meaning that mip-dna does not fail the analysis when relationships aren't correct. In the validation data I've looked in the folders 200814 (version 9.0) and 20210428 (version 10.0) for case `cleanshrimp` and the file `cleanshrimp_qc_metrics.yaml` in the folder qccollect_ar contains this "relation_check: PASS". This is missing under the folder 20211104 (version 11.0).

I have sent the caseID of a case that should have failed on this in production to @jemten, not including it here. 

**Expected behavior**
Perform the check and if needed fail analysis.

**Software version (please complete the following information):**
 - MIP: 11.0

**Additional context**

**Comment by jemten** [comment]
Thanks for submitting. I'll have a look!
