### ISSUE TITLE
Request to update initiation maps

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/MIP#2058]
The files `https://github.com/Clinical-Genomics/MIP/blob/master/definitions/rd_dna_initiation_map.yaml`and `https://github.com/Clinical-Genomics/MIP/blob/master/definitions/rd_rna_initiation_map.yaml` are referred to from the method document of mip in atlas. This is a request to look over those files so that they are up to date with the version in production, for example haplotypecaller is listed in the dna file.

**Comment by jemten** [comment]
It's the same version that is used in production today. The initiation map does not control which programs that are executed rather it controls their order and dependencies on other programs. The programs that are executed are controlled by the cli, config and default settings, https://github.com/Clinical-Genomics/MIP/blob/60cdffb57bced897a7bf223028ad943371ff0ac9/definitions/rd_dna_parameters.yaml#L1438, as well as which programs that are compatible with the analysis type, ie wgs or wes.
