### ISSUE TITLE
Fail analysis on error in Peddy

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/MIP#2059]
**Is your feature request related to a problem? Please describe.**
Today it's routine for prod bioinfo to manually inspect the mip-dna cases in Scout, one part of this is to inspect the sample table to see that there is no exclamation mark under sex or kinship, which means that the sample has failed these checks in Peddy. There is no checks for this in mip-dna today, I think it would be good to include this so that we can remove this manual work from prod bioinfo. 

**Describe the solution you'd like**
Make mip-dna fail on problem with sex and relationships in Peddy.

**Additional context**
This is a screenshot of the sample table in Scout from the case mentioned in #2057, where sex is correct according to Peddy but reporting failure for the relationships. 

<img width="758" alt="Screenshot 2023-10-23 at 11 18 52" src="https://github.com/Clinical-Genomics/MIP/assets/19236050/95f3638b-0452-43d6-a133-d6cce39197ca">

**Comment by jemten** [comment]
MIP is not under active development and thus this feature will not be implemented in the pipeline. However, the feature you're requesting would be very useful and we will implement it when we bring the new nextflow pipeline into production.

**Comment by moahaegglund** [comment]
> MIP is not under active development and thus this feature will not be implemented in the pipeline. However, the feature you're requesting would be very useful and we will implement it when we bring the new nextflow pipeline into production.

Sounds great!

**Comment by pbiology** [comment]
We are now looking to [improve the way we do delivery](https://github.com/Clinical-Genomics/project-planning/issues/515) of MIP (and other pipes) cases in Scout, and part of this would be to remove the manual check in Scout by prodbioinfo. For this to work we would need this to be implemented.

The idea of not pushing for MIP but rather nf-core/raredisease is solid, but we should evaluate the timeline hear since it could help out the production quite a bit.

**Comment by jemten** [comment]
We could also look into implementing this in CG. Long term we want to have this check in maven or a program using the maven db, but that is probably further away. I can do this check in MIP fairly easy but the qc-checks are moving to CG for the new rd pipeline, pending maven.
