### ISSUE TITLE
Variant not called in MIP-analysis

### ISSUE THREAD

**Issue by AnnHam** [Clinical-Genomics/MIP#2071]
Issue: Case F0059468 (cust002) have a pathogenic variant in KRT6B that was not called in the WGS analysis. We found out that our patient's sister with the same disease was analyzed in another laboratory and got a genetic diagnosis. So by backtracking in IGV we see the variant. 

The variant is NM_005555.4 (KRT6B):c.516_518del p.(Asn172del) - Location chr12:52,845,345-52,845,347 (hg19)

In IGV it looks a little bit skewed but still 9 reads with the alternative allele (24 reads with the reference allele).

**Comment by dnil** [comment]
Not found in either selected or unselected VCFs; perhaps missed by DeepVariant?

**Comment by dnil** [comment]
Seen three times in gnomAD exomes (two from 2.1 / grch37). https://gnomad.broadinstitute.org/variant/12-52451560-CTTG-C?dataset=gnomad_r4. No genomes, fwiw.

**Comment by jemten** [comment]
Deepvariant version calls it as reference, assigning the alt 9 reads out of 29 and with a low quality score. I'll dig into it a bit more.
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	ACC14142A3
12	52845344	.	CTTG	C	2.2	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:4:29:20,9:0.310345:0,1,30
```

**Comment by jemten** [comment]
Looks like the reads supporting the deletion are being split between KRT6B and KRT6C. 
Ran BLAT for a couple of the deletion supporting reads and those map equally well to either of the genes.
<img width="2162" alt="image" src="https://github.com/Clinical-Genomics/MIP/assets/3168925/83c2e1dd-a724-4524-aa6a-c56545029b47">
<img width="2149" alt="image" src="https://github.com/Clinical-Genomics/MIP/assets/3168925/052ea6af-0af6-4257-b969-d650a83a6a2b">

**Comment by jemten** [comment]
Closing this for now. We can try to include this case in future testing to see if it the variant pops up with grch38, new variant caller or long read. Please reopen if you have more questions

**Comment by dnil** [comment]
It may also be interesting to test a tool like https://github.com/Ensembl/VEP_plugins/blob/release/112/Paralogues.pm, but perhaps that is more for nf-core/raredisease.

**Comment by jemten** [comment]
That could be a very nice plugin to add. Doesn't look like it takes a bam file so I guess it rely on the variant being found on at least one of the paralogs. Or maybe it does something clever with the read support from the VCF? Anyway it would be good to test this plugin

**Comment by dnil** [comment]
Yes, most likely relying on calls on at least one. And the paralogues would likely not be in the clinical list, so would require a research level annotation. But still.
