### ISSUE TITLE
Plink sex check hotfix for unknown sex gives error:

### ISSUE THREAD

**Issue by Dilea** [Clinical-Genomics/MIP#218]
Error: When ambiguous-sex samples with phenotype data are present,
--make-bed/--make-just-fam/--recode/--write-covar usually cannot be combined
with other commands.  Split them across multiple PLINK runs, or use
--allow-no-sex/--must-have-sex.

**Comment by henrikstranneheim** [comment]
Made another hotfix (mip v5.0.11). It was further upp in the plink processing than I thought. Hopefully now it will allow the unknown gender and skip the plink sex check. Go ahead and try it. Let me know if the problem persists.
