### ISSUE TITLE
Evaluate ExpansionHunter

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#252]
ExpansionHunter from Illumina.

http://genome.cshlp.org/content/27/11/1895

**Comment by dnil** [comment]
Yep! 

I have good test data for that - different known expansions from different genes - in the rerun queue. Let me know when it’s time to test.. :)

**Comment by henrikstranneheim** [comment]
Perfect!

**Comment by dnil** [comment]
Tested for 9 cases w FRAX/FMR1, HTT, ATXN1, ATXN2, ATXN3, DM1/DMPK with acceptable results. Separation between normal and pathogenic or pre-mutation was achieved, although the exact number of repeats was not found for larger alleles. A quick and simple install and run. Uses bam, produces VCF. Recommended for implementation.

**Comment by henrikstranneheim** [comment]
Fantastic. Could you provide the run specs and then we can add into MIP in the near future

**Comment by dnil** [comment]
HUNTER_DIR=ExpansionHunter-v2.5.5-linux_x86_64

$HUNTER_DIR/bin/ExpansionHunter --repeat-specs $HUNTER_DIR/data/repeat-specs/grch37/ --ref-fasta $GENOME_FASTA--sex $SEX --bam  ${SAMPLE}.bam --vcf $SAMPLE_OUTPUT.vcf --json $SAMPLE_OUTPUT.json --log $SAMPLE_OUTPUT.log

**Comment by dnil** [comment]
I used the current release: https://github.com/Illumina/ExpansionHunter/releases/tag/v2.5.5

**Comment by henrikstranneheim** [comment]
👍

**Comment by henrikstranneheim** [comment]
Recorded in qc_sampleinfo.yaml:
```
[FAMILY_ID]:
  expansionhunter:
    Path: [path/file.vcf]
```

**Comment by dnil** [comment]
Nice! Just checking: it is split as well, so that there is only one alt allele per VCF line?

**Comment by henrikstranneheim** [comment]
No, good point! I will add it. Do you want a decompose for each sample vcf before merge or is it enough to decompose the family vcf?

**Comment by dnil** [comment]
Family level should be fine! I zipped and index the ones I tested loading; pretty redundant for this small a VCF but perhaps good for consistency?

**Comment by henrikstranneheim** [comment]
Sure! You mean vcf.gz with .csi?
