### ISSUE TITLE
vcf2cytosure 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#280]
https://github.com/NBISweden/vcf2cytosure/releases/tag/0.2.0

Note that the easiest way to get good coverage data is to enable TIDDIT coverage output.
See TIDDIT readme or ask @J35P312 for details.. :smile:

**Comment by northwestwitch** [comment]
I've introduced tiddit coverage module so we're going to use it when generating coverage data to run vcf2cytosure. Almost done with this recipe by the way. If you agree we could close the issue.

**Comment by henrikstranneheim** [comment]
Let's merge and close the pull request first.

**Comment by henrikstranneheim** [comment]
Seems like the vcf2cytosure is dependent on libxml2 and libxslt being present in the conda environment (conda install libxml2 libxslt). 
@northwestwitch Could you add these as dependecies in mip_install.pl? Ask @jemten for instructions.

**Comment by northwestwitch** [comment]
Ok!

Chiara

**Comment by henrikstranneheim** [comment]
Test runs look ok. @dnil @J35P312 I have added a MIP produced vcf2cytosure file (Hapmap sample) to your INBOX: ADM1059A1_sorted_md_brecal_comb_SV.cgh. Please try and load it into cytosure to see that it looks like you expect.

**Comment by dnil** [comment]
Cool! I’ll pass it on to Johanna Lundin!

// Daniel
