### ISSUE TITLE
Add adapter sequence to input per library preparation (LB)

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#304]
Tentative approach:
- [ ] Get index for sample per library preparation and read direction from LIMS
- [ ] Record in StatusDb
- [ ] Supply to analysis

**Comment by ingkebil** [comment]
To summarize the discussion with @hassanfa 

- we are currently not trimming adapters from the fastq files durign demuxing
- bcl2fastq version we are using has the option to do so
- if no extra options are needed for bcl2fastq, it would be possible to add this to the generated SampleSheet.csv for RNA and cancer samples

**Comment by henrikstranneheim** [comment]
Stale and hard to accomplish in current production setting
