### ISSUE TITLE
Add GATK version 4

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#306]
- [x] mip_install.pl
- [x] gatk base command
- [ ] gatk commands 
  - [x] BaseRecalibrator
  - [x] ApplyBQSR
  - [x] HaplotypeCaller
  - [x] PrintReads
  - [x] GenomicsDBImport
  - [x] GenotypeGVCF
  - [x] GatherVCFs
  - [x] VariantRecalibratior
  - [x] ApplyVQSR
  - [x] VariantFiltration
  - [x] ASEReadCounter
  - [x] CalculateGenotypePosteriors
  - [ ] CombineVariants [Not ported to gatk4]
  - [ ] VariantEval --> [Not ported to gatk4]
  ...
- [ ] analysis recipes
  - [x] BaseRecalibrator
  - [x] ApplyBQSR
  - [x] HaplotypeCaller
  - [x] GenomicsDBImport
  - [x] GenotypeGVCF
  - [x] GatherVCFs
  - [x] VariantRecalibratior
  - [x] ApplyVQSR
  - [x] VariantFiltration
  - [x] ASEReadCounter
  - [x] CalculateGenotypePosteriors
  - [ ] CombineVariants [Not ported to gatk4]
  - [x] LeftAlignAndTrimVariants --> bcftools norm
  - [ ] VariantEval [Not ported to gatk4]
  ...
- [x] mip.pl

**Comment by jemten** [comment]
Closing this issue for now. Will look into alternatives to combinevariants and varianteval
