### ISSUE TITLE
test for MIP::File::Format::Pedigree qw{gatk_pedigree_flag}

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/MIP#343]

**Comment by northwestwitch** [comment]
@henrikstranneheim can I use the file data/643594-miptest/643594-miptest_pedigree.yaml to run this test, or is expecting something different?

**Comment by henrikstranneheim** [comment]
No i think it operates on a ".fam" file. We should add one to the test data. Check with @jemten
