### ISSUE TITLE
Evaluate Svtyper

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#346]
https://github.com/hall-lab/svtyper

**Comment by J35P312** [comment]
I tested SVTyper. It worked great for some callers and variant types. But in essence, it assumes that you are using Lumpy. For instance, all variants marked "DUP" will be treated as tandem dup. And variants labeled TDUP will be skipped.

I will keep looking for some other tool!

**Comment by henrikstranneheim** [comment]
👍
