### ISSUE TITLE
A feature to evaluate integrity of BED file

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/MIP#359]
We might need a new feature to evaluate the integrity and type of BED file. We might as well use the description provided by https://www.ensembl.org/info/website/upload/bed.html .

The checks that might be useful to provide should include at least the following:

1. Column data type validation (e.g. chromStart/End shouldn't be non-number)
2. Column data integrity (e.g. no space within any of the first 8 fields)
3. A thorough validation (e.g. whole file) vs snapshot validation (e.g. first N lines)
4. Check integrity of delimiters within fields

**Comment by henrikstranneheim** [comment]
http://search.cpan.org/~tjparnell/Bio-ToolBox-1.53/lib/Bio/ToolBox/Data.pm

This might be useful.
