### ISSUE TITLE
Input bed file is set as mandatory and it is breaking the tests

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/MIP#386]
https://github.com/Clinical-Genomics/MIP/blob/58602267115e372e0aef62313d0253d387c9e4e7/definitions/define_parameters.yaml#L1539

**Comment by henrikstranneheim** [comment]
I think this was fixed by @jemten in the last PR

**Comment by hassanfa** [comment]
Didn't notice that it is fixed in #385 .
