### ISSUE TITLE
Add AddOrReplace read group

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#389]
- [x] Add picard command 
- [x] Add test for command
- [x] Add to star aln recipe

**Comment by henrikstranneheim** [comment]
@J35P312 Will you continue with adding the command to the recipe?

**Comment by J35P312** [comment]
Good evening!
I will give it a try next week!

**Comment by henrikstranneheim** [comment]
👍

**Comment by J35P312** [comment]
done!
