### ISSUE TITLE
SLURM parameters

### ISSUE THREAD

**Issue by xexpanderx** [Clinical-Genomics/MIP#421]
Hi,

Is it possible to control SLURM parameters like which partition a job should be submitted to? I cannot see this possibility looking at help (mip --help).

We have several partitions and is therefore crucial for us to be able to specify the partition, cores nodes, e.t.c.

Thank you.

**Comment by henrikstranneheim** [comment]
These flags are currently supported:

"--project_id X" = #SBATCH --account=X

"--module_core_number "program_name"=X(cores))" = #SBATCH --ntasks=1

"--module_time ("program name"=time(Hours))" = #SBATCH --time=1:00:00

"--slurm_quality_of_service" = #SBATCH --qos=low

"--email" = #SBATCH --mail-user=

"--email_types" = #SBATCH --mail-type=FAIL

Could you be more specific in what you additionally would like to have and I will look into if it is possible?

**Comment by henrikstranneheim** [comment]
Closing this. Please open a new issue with more specific requests.
