### ISSUE TITLE
Level of detection for heteroplasmi

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#507]
Currently MIP's variantcallers are unable to pick up a mitochondrial variant supported by 9% of the NGS reads. The variant has been confirmed using orthogonal methods

**Comment by jemten** [comment]
Temporarily fixed by increasing ploidy to 3 for MT, pushed to master and develop (#511, #510 ). Will do a more thorough investigation.

**Comment by henrikstranneheim** [comment]
Evaluate for GATK 4. GATK 4 will probably fix this issue by default.

**Comment by jemten** [comment]
Mutect2 might be an alternative for calling variants on the mitochondria.
https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_walkers_mutect_Mutect2.php

**Comment by jemten** [comment]
Sure! I'll slack you the path

**Comment by jemten** [comment]
Ran HaplotypeCaller and GenotypeGVCFs from GTAK4 on the bam file and the variant is picked up. Heteroplasmy level of ~10%. Would be interesting to do a more thorough investigation with lower levels of heteroplasmy using mutacc later

**Comment by henrikstranneheim** [comment]
👍
