### ISSUE TITLE
MIP 6 manipulates ID field in VCF?

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/MIP#508]
Seems like the CLINVAR accession number is added to the ID field, is that the expected behaviour? There is already CLNVID in the INFO field that includes the information.
Just to be clear, an example for how the ID column looks: `rs11214077;6909`.

**Comment by henrikstranneheim** [comment]
It is in the ID field from CLINVAR centrally. I have preprocessed the Clinvar file in the download process and migrated it to the INFO field to standardise the use in MIP. This simplyfies the process for some annotation programs. Use of either one in Scout should be fine.
