### ISSUE TITLE
One case one Multiqc report

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/MIP#515]
Hi, as far as I can see at the moment there is one MultiQC report produced for each individual. Is it possible to create one report per case or merge the reports?

**Comment by henrikstranneheim** [comment]
Should not be a problem! Glad to see we are finally utilising multiqc 😄!

**Comment by henrikstranneheim** [comment]
Will look like this in qc_sample_info:
``` 
 multiqc:
    643594-200M:
      path:PATH/643594-200M/analysis/643594-200M/multiqc/multiqc_report.html
    ADM1059A1:
      path: PATH/643594-200M/analysis/ADM1059A1/multiqc/multiqc_report.html
```

Control report per sample using option: "--multiqc_per_sample"

**Comment by henrikstranneheim** [comment]
Done
