### ISSUE TITLE
URGENT: MIP6 rename bcf.gz to bcf

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/MIP#516]
It seems cyvcf2 is throwing an assertion error when plain bcf files are named bcf.gz:

```
  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/stage/lib/python3.6/site-packages/genotype/load/vcf.py", line 58, in fetch_snp
    variants = list(vcf(pos_str))
  File "cyvcf2/cyvcf2.pyx", line 371, in __call__
AssertionError: error loading tabix index for b'/mnt/hds/proj/bioinfo/STAGE/bundles/cuddlyoryx/2018-06-14/cuddlyoryx_sorted_md_brecal_haptc_BOTH.bcf.gz'
```

According https://github.com/brentp/cyvcf2/issues/46 renaming bcf.gz to bcf fixes the issue. I tried that and it worked :)

what do you think? Can you have MIP6 spit out bcf files instead bcf.gz?

**Comment by ingkebil** [comment]
Also opened an issue with cyvcf2: https://github.com/brentp/cyvcf2/issues/85

**Comment by henrikstranneheim** [comment]
MIP produces the .csi index (bctools) for that file. I can switch to producing the .tbi (tabix) index instead.

**Comment by ingkebil** [comment]
That's not the problem. The problem is the .gz extension. When I remove
that, pyvcf2 works.

wkr,
Kenny
--
Composed and sent on the road

**Comment by jemten** [comment]
I'll change MIP to have it produce the  bcf file without the .gz extension :)

**Comment by jemten** [comment]
Is the [FAMILY]_sorted_md_brecal_haptc_BOTH.bcf.gz file used by any other programs downstream of MIP or can I skip generating that file?

**Comment by ingkebil** [comment]
As far as I can tell, we have been using only the bcf file up until now. It
is OK to skip generating that file.

Thanks!

wkr,
Kenny
--
Composed and sent on the road

**Comment by jemten** [comment]
OK, then I will only generate the compressed bcf file and give it a .bcf extension.  

Later in MIP we generate other compressed bcf file with the .gz extension, such as:
[FAMILY]_sorted_md_brecal_comb_SV.bcf.gz
[FAMILY]_sorted_md_brecal_haptc_vrecal_comb_BOTH.bcf.gz
Are these causing issues as well?

@henrikstranneheim, found an old issue on discussing file extensions of bcf files [#114](https://github.com/samtools/hts-specs/issues/114) Reading this it sounds like it might be an idea to drop the bcf.gz extension and have both compressed and uncompressed bcf files using the .bcf extension. Maybe a discussion for later...

**Comment by ingkebil** [comment]
As far as I can tell, we are not using that file downstream at all and it will be delivered as such.

I would still prefer to have it named without the .gz extension for the sake of consistency.

Thanks!

**Comment by ingkebil** [comment]
... and how do I update?

**Comment by ingkebil** [comment]
Nvm, figured it out

**Comment by henrikstranneheim** [comment]
👍
