### ISSUE TITLE
local SVDB dump

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#523]
While waiting for the next release of loqusdb, an SVDB dump for a few hundred local cases would help with site-specific variants.

**Comment by J35P312** [comment]
Sounds like a good idea! Can we use the database of our 100 samples on Bianca?

**Comment by J35P312** [comment]
That sounds great! Yep, I can move them to Bianca next time I visit scilife =P

**Comment by henrikstranneheim** [comment]
Processed: 2217 (mostly WGS) samples into SV frequency db and export vcf and inlcuded in analysis using svdb query. 
Done! 
Thx for the help - @dnil @J35P312 @moonso!
