### ISSUE TITLE
List of sambamba coverage thresholds have changed

### ISSUE THREAD

**Issue by b4ckm4n** [Clinical-Genomics/MIP#533]
List of sambamba coverage thresholds used to be:
- 10
- 15
- 20
- 50
- 100

But now it's:
- 10
- 20
- 30
- 50
- 100

Could we change it back?
/DB

**Comment by henrikstranneheim** [comment]
Of course. Set it in your global config.

/H

Skickat från min iPhone

**Comment by henrikstranneheim** [comment]
Changed defaults! Done!

**Comment by emiliaol** [comment]
This problem has cropped up in production v6 again
