### ISSUE TITLE
Use STAR output for STAR-fusion

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#587]
Now STAR-fusion runs it's own mapping but there is an option to have STAR-Fusion operate on the output from STAR. 
Some updates to the STAR aln command is required:
  - Update STAR aln with STAR-fusion parameters
  - Run STAR on all sample fastq files (e.g. no separate jobs for different lanes)

**Comment by henrikstranneheim** [comment]
Closing this for now
