### ISSUE TITLE
Splicing program - BRCA

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/MIP#598]
Regarding prediction of splicing of the BRCA genes this program is recommended/validated:

http://genes.mit.edu/burgelab/maxent/Xmaxentscan_scoreseq.html

Would it be possible to include this in the pipeline - esp for the tumour samples?
// Kicki

**Comment by henrikstranneheim** [comment]
Yes absolutely, Actually we already have this in the pipeline via VEP, but we have not added it to the rank model yet and not to Scout.

We can try to get it in the rank model by MIP 7.0 and perhaps faster to displaying in Scout (@moonso , @northwestwitch ).

**Comment by henrikstranneheim** [comment]
Done. Will validate rank model before pushing MIP7.0.
