### ISSUE TITLE
Trailblazer can't run mip with 0 as expected coverage

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/MIP#606]
@emiliaol reports that "Trailblazer throws an error when you try to start an analysis of WGXCUSC000 that has been set to 0 expected coverage. It just says that there is no expected coverage for the sample. Changing expected coverage to 1 solved the issue.

After looking a bit more closely it might be mip that's causing the issue:
MIP - Could not find value for ADM1524A19 for parameter '--expected_coverage'
File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/trailblazer/mip/start.py", line 44, in __call__ raise MipStartError('error starting analysis, check the output') trailblazer.exc.MipStartError: error starting analysis, check the output"

**Comment by henrikstranneheim** [comment]
Why would you expect 0 coverage from a sequencing run? That means that you have not sequenced at all.

**Comment by henrikstranneheim** [comment]
If you do not want to use "--expected_coverage" in the analysis - Then try to not inlude it when creating the pedigree file. I do not think that would casue any problems.

**Comment by vwirta** [comment]
When we put 0 coverage this means that we do not give any guarantees re quality of the sequencing (remember we guarantee 75% of expected).

For example, for externally sequenced samples we would not guarantee anything

VW


----
Valtteri Wirta, PhD
Enhetschef / Head of unit, Clinical Genomics, Science for Life Laboratory
MTC, Karolinska Institutet
valtteri.wirta@scilifelab.se | +46 8 5248 1545 | Box 1031, 171 21 Solna
Visiting address: Tomtebodavägen 23 A, 171 65 Solna

**Comment by henrikstranneheim** [comment]
yes, what you want is - do not perform the expected coverage analysis i.e. do not put the parameter in the pedigree file.

**Comment by henrikstranneheim** [comment]
Closing this, sending it back to trailblazer
