### ISSUE TITLE
Custom expansionhunter file for KUL

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#618]
- CMMS genes
- Clinisk genetic

**Comment by dnil** [comment]
New json available from forked repo https://github.com/dnil/ExpansionHunter
STRs: AFF2, ATXNO8OS, CNBP, NOP56, PAPBN1, TBP.

**Comment by dnil** [comment]
I've now PRed that to the main repo, but it is probably wise to have a local way to add new repeat specs anyway.

**Comment by henrikstranneheim** [comment]
FYI: I have asked Nicole and the other for regions that CMMS is interested in - so it's coming as well

**Comment by henrikstranneheim** [comment]
Will make a repo at clinical for these utility files

**Comment by henrikstranneheim** [comment]
I have created a repo in Clinical genomics: https://github.com/Clinical-Genomics/reference-files and added POLG.json.

@dnil Please add your custom files there, so that we can download them and include them in MIP7.0.

**Comment by henrikstranneheim** [comment]
Done
