### ISSUE TITLE
vcf2cytosure CGH 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#621]
- [ ] Sample names given in CGH files are facility internal ones. Should be customer IDs. Gathered from file name by vcf2cytosure. Either rename (or link) file to external id before running, or pass the issue on to vcf2cytosure to add a command line option.
- [ ] consider compressing CGH files: 20x reduction in size, for what is currently on the order of 100 Mb files. Will shrink with better filtering. Worth the effort?

**Comment by jemten** [comment]
Having discussed with @dnil we agreed that the names should be converted from internal to external outside MIP.  MIP can easily compress the CGH files. However, the end user probably wants the files to be uncompressed and ready to use once they're downloaded. Until that solution is implemented (in Scout?) we're leaving the files in their current state. 

Reopen this issue if compression is indeed needed.
