### ISSUE TITLE
CADD indels

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#623]
Run CADD locally on indels that were not already pre-tabulated for CADD. See Scout issue [#333](https://github.com/Clinical-Genomics/scout/issues/333).

**Comment by henrikstranneheim** [comment]
Done!
@dnil @jesper: Time to start looking at #594

**Comment by henrikstranneheim** [comment]
Will require a manual install outside of MIP as the installation process is less than ideal and currently (CADD v1.4) is not compatible with automated installation via MIP.
- To enable CADD for indels in MIP: 
  1. Install CADD using instructions at: https://github.com/kircherlab/CADD-scripts
  1. Move the installed local CADD base dir to the MIP conda base env share dir. 
  1. Add a softlink to "CADD.sh" in the MIP conda base env bin dir from the manuall CADD.sh installation in dir share.

**Comment by jesper** [comment]
> Done!
> @dnil @jesper: Time to start looking at #594

Wrong Jesper 😳

**Comment by dnil** [comment]
Right, should be @J35P312! Sorry; more 13375P38K to the ppl..
