### ISSUE TITLE
Update how environments are activated

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#628]
As of conda 4.4 the preferred way of activating a conda environment is `conda activate [ENV]` and to deactivate an environment `conda deactivate`. The old way still works but the new commands are faster and plays nicer with other scripts. 
It is also recommeded to update the .bashrc file to include: 
```
\. [PATH_TO_CONDA]/etc/profile.d/conda.sh
conda activate base
```
instead of adding conda bin to path.

**Comment by henrikstranneheim** [comment]
Done
