### ISSUE TITLE
Include Stranger in rare disease pipeline

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/MIP#653]
Hi,

we have created a small tool, [stranger](https://github.com/moonso/stranger), to annotate str variants. Could you include that in the Expansion Hunter block? It's installable from PyPI with `pip install stranger` and to run it simple use `stranger <path-to-vcf>` and it will print a annotated VCF to stdout with the new info field (and header) `STR_STATUS`.

**Comment by henrikstranneheim** [comment]
Done
