### ISSUE TITLE
Evaluate adding CCR score annotations 

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#674]
Local region constraints scores (more detailed than e.g. pLI) from the Quinlan lab. Looks interesting - see https://www.nature.com/articles/s41588-018-0294-6 - but I haven't tried them out. Probably a decent bit of circular reinforcement on the results when comparing to other methods, but the thought is good. Bed tracks for download with the paper: https://s3.us-east-2.amazonaws.com/ccrs/ccrs/ccrs.autosomes.v2.20180420.bed.gz and https://s3.us-east-2.amazonaws.com/ccrs/ccrs/ccrs.xchrom.v2.20180420.bed.gz.

**Comment by henrikstranneheim** [comment]
Stale - let's work on improving annotations in https://github.com/nf-core/raredisease
