### ISSUE TITLE
GT call: genotype and read do not fits toegether

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/MIP#681]
Discussion from https://github.com/Clinical-Genomics/scout/issues/1098 should continue here

**Comment by henrikstranneheim** [comment]
Will switch calculate genotype posterior off in MIP7.0. This will create less confusion downstream in Scout.

**Comment by henrikstranneheim** [comment]
Default for MIP is now to not use calculate genotype posterior unless asked to do so (and then only for trios).
