### ISSUE TITLE
Rename sample_origin to is_from_sample

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#692]

**Comment by henrikstranneheim** [comment]
@ingkebil @emiliaol : Would be great if CG could name the sample_source as is_from_sample in the future. I will start on the standardization terminology early next year.

**Comment by ingkebil** [comment]
I heard somewhere that Swedes love consensus. What do you think about suggesting the list of standardized terms and we all have a meeting on it, see if anyone foresees any problems?

First question I have is if you're following any known variable naming conventions? e.g. Perl Best Practices, as far as I remember, has the following conventions: use the `is_` prefix with bools, name maps with `name_of[item]` and array names are plural `items`. Wat do you think about trying to following something similar where it seems applicable?

**Comment by henrikstranneheim** [comment]
This is perfectly fine for a PBP for a hash key using a singular noun followed by a preposition, using multiple identifiers seperated by underscores and does not brake any rules and yes we follow PBP (slavishly). 
You, me and Emilia already decided this one on the RNA-meeting a couple of weeks ago. I have no problem with following a convention, but CG is python and MIP is perl and the variable will be used across Clinical Genomics, with LIMS and bash and what not, so the it hard to know which convention to use. Most important is probably that the identifier "should clearly and accurately reflect the purpose, usage, and significance of whatever you’re naming". I am going to go with "is_from_sample" for MIP 7, so that I can run some validation runs during the holidays and we can do what you suggest in January. It should be easy to adapt to what ever we decide upon in a later version.  We can also discuss if we should allow differences in syntactic consistency between tools (I think so).
