### ISSUE TITLE
Evaluate regulatory mutation scores

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#726]
Scoring of pathogenic intergenic or intronic regulatory variants is lacking,

Could we evaluate what's on the smorgasbord now, e g ReMM/Genomiser (https://www.cell.com/ajhg/fulltext/S0002-9297(16)30278-6) and NCBoost (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1634-2).

CADD, frequency and conservation does a little to help, as does frank dbs of known pathologic variants e.g. ClinVar or a local dito, but can never cover the full range.

**Comment by henrikstranneheim** [comment]
This one also looks interesting: https://www.nature.com/articles/s41588-018-0062-7

**Comment by henrikstranneheim** [comment]
Stale
