### ISSUE TITLE
Wrong genotyping (from scout)

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/MIP#752]
This is transferred from https://github.com/Clinical-Genomics/scout/issues/1153

**Describe the bug**
Problematic genotype call

**To Reproduce**
1. Submit recipe '...'
2. Go to '....'
3. Open log '....'

**Expected behavior**

**Screenshots**

**Software version (please complete the following information):**
 - MIP: [e.g. 6.0.12]
 - 

**Additional context**

**Comment by henrikstranneheim** [comment]
I believe this is an internal freebayes issue relating to the haplotype algorithm. There is no bug in MIP as far as can tell.
Closing this, please reopen if there is a more detailed MIP change you would like to see in MIP.
