### ISSUE TITLE
Evaluate uORF VEP plugin

### ISSUE THREAD

**Issue by genecracker** [Clinical-Genomics/MIP#755]
Hi again,

Another VEP plugin from the gnomAD work, this time to annotate 5'UTR variants.
https://github.com/ImperialCardioGenetics/uORFs

see even this twitter for good summary: 
https://twitter.com/nickywhiffin/status/1093847642117947392

Kind regards,
Bianca

**Comment by henrikstranneheim** [comment]
Thx for submitting this Bianca! Looks interesting! We will check it out.

**Comment by henrikstranneheim** [comment]
Let's revisit VEPs plugins in https://github.com/nf-core/raredisease
