### ISSUE TITLE
gnomAD-SV integration - heads up!

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#760]
https://www.biorxiv.org/content/10.1101/578674v1. 15k genomes with SV from gnomAD. Annotations a little further diversified towards the complex as well it seems, so expect some integration of tools to follow. Feel free to start working on it, but it is also something that I and @J35P312 will likely pursue. I couldn't find the actual data on gnomAD yet; guessing to be released when paper accepted?

**Comment by henrikstranneheim** [comment]
Fabulous! Will follow and include when appropriate.

**Comment by J35P312** [comment]
Looks nice! I see they run Manta, Delly, cnvnator, as well as some other callers, as such, it should match MIP very nicely! They run the pipeline presented here:  

An analytical framework for whole-genome se-
quence association studies and its implications for autism spectrum 
disorder.

**Comment by dnil** [comment]
VCF at the very bottom of the page here: https://gnomad.broadinstitute.org/downloads/

**Comment by dnil** [comment]
https://storage.googleapis.com/gnomad-public/papers/2019-sv/gnomad_v2_sv.sites.vcf.gz

Says "sites", but kind of hope they have frequencies there as well?

**Comment by J35P312** [comment]
Thanks! yes, it do have a lot of frequency information!
I have tested on a single file using SVDB as annotation tool, It seems to work relatively well! I will make some  plots next week =P

**Comment by J35P312** [comment]
I must add that it is a nice database, but it  contains  less than 500 000 SVs, the swegen dataset contains 1 654 551 SV, and our old NGI db contains 1 044 410 SV, so it is either filtered to contain only high quality calls, or heavily merged.

**Comment by henrikstranneheim** [comment]
- [ ] Create new download recipe 
- [ ] Remove multiallelics in post processing in download recipe
- [ ] Update svdb, to version capable of handling gnomadSV
- [ ]  Use new info key naming in svdb to tag gnomad info keys
- [ ] Add to svdb query files
- [ ] Add to sv_rank_model
- [ ] Relay info to Scout in issue

**Comment by henrikstranneheim** [comment]
Done
