### ISSUE TITLE
gnomAD MNV

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#761]
These guys are really productive! 

A current solution to MNV extraction:

https://github.com/macarthur-lab/gnomad_mnv

Described in:

https://www.biorxiv.org/content/biorxiv/early/2019/03/10/573378.1.full.pdf

Pretty common with stop-gain-rescue - and occasionally the reverse - so well worth investigating.

With VCF data on gnomAD available at

https://gnomad.broadinstitute.org/downloads/

**Comment by henrikstranneheim** [comment]
Will not add in MIP. Could be discussed in https://github.com/nf-core/raredisease when the time comes
