### ISSUE TITLE
Update Expansionhunter

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#771]
- [x] Install Expansionhunter
- [x] Reference download from Clinical Genomics
- [x] Command
- [x] Recipe
- [x] Cli (variant_catalog_file_path) 
- [x] Update Stranger

**Comment by henrikstranneheim** [comment]
Basically done with MIP part. Only merging of user json with Expansionhunter and updating stranger left. @moonso @dnil - Ready when you are...

**Comment by dnil** [comment]
Ok! We will have a look later this week!

**Comment by henrikstranneheim** [comment]
👍

**Comment by henrikstranneheim** [comment]
Done

**Comment by dnil** [comment]
Oops; turns out the ExHu v3.0.0 has changed REPID naming convention compared to the v3rc-series. Needs Stranger 0.5.2 to work well now. Available on PyPi and git.
