### ISSUE TITLE
Add variant splicing scores from spliceAI 

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#775]
Annotate variants with a splicing score from the spliceAI model. For each variant there is a donor_gain, donor_loss, acceptor_gain and acceptor_loss score. Scores above 0.8 seems to highly penetrant across tissues and lower scores are more tissue dependant. There are precomputed scores for hg19 available.
[Article](https://www.sciencedirect.com/science/article/pii/S0092867418316295)

Also there is a VEP plugin: https://github.com/Ensembl/VEP_plugins/blob/release/99/SpliceAI.pm

**Comment by moonso** [comment]
Hi, when you have decided what the vcd keys should be called, can you post that in https://github.com/Clinical-Genomics/scout/issues/1250 ?

**Comment by jemten** [comment]
MIP now annotates SNV:s, 1bp insertions and 1-4bp deletions using the following files from illumina: `spliceai_scores.raw.snv.hg37.vcf.gz` and `spliceai_scores.raw.indel.hg37.vcf.gz`.
