### ISSUE TITLE
Trailblazer input file for monitoring MIP run

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#777]
- Place in case/analysis/mip_log/[DATE]/slurm_job_ids_[DATE_TIME_STAMP].yaml
FORMAT:
case:
 - job_id_1
 - job_id_2

**Comment by henrikstranneheim** [comment]
@emiliaol Basically done! If you want to change location, filename or format. Let us know - should be a very easy fix!

**Comment by emiliaol** [comment]
Super!

**Comment by emiliaol** [comment]
@ingkebil Please have a look at our suggested job id list for trailblazer+. Looks ok?
