### ISSUE TITLE
Add MELT support

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/MIP#805]
**Is your feature request related to a problem? Please describe.**
Transposable element detection is of interest for hereditary disease, presumably at a below 1% of cases level.

**Describe the solution you'd like**
We would like to see TE detection implemented, initially through running of MELT. 
See https://github.com/J35P312/SMELT for a nextflow wrapper with config (cheers to Diana E and @J35P312). It will produce VCF output, that can be made compatible with downstream tools.

Merging with SV variants can add information to the prior, showing which BNDs / decoy hits are actually 

A database will be needed for making the output easily screenable. We have an svdb with the 1000 SweGen cases for this; should be available from SweFreq? I am unsure about if this was done on the Decoy hg19 and hg38 as well - @J35P312?

**Comment by henrikstranneheim** [comment]
Pricing looks to expensive according to mail from @dnil

**Comment by dnil** [comment]
Let's look into RetroSeq and perhaps particularly a nearby fork instead: https://github.com/J35P312/RetroSeq

**Comment by henrikstranneheim** [comment]
👍
