### ISSUE TITLE
Supply toml files for vcfanno

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#826]
**Is your feature request related to a problem? Please describe.**
Vcfanno requires a set of toml files that are not currently shipped with MIP or downloaded/created by MIP

**Describe the solution you'd like**
Supply examples of toml files for vcfanno in templates

**Describe alternatives you've considered**
Create toml files on the fly

**Comment by henrikstranneheim** [comment]
Done by #847 #844
