### ISSUE TITLE
Download references

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#828]
**Is your feature request related to a problem? Please describe.**
Some references are not downloaded by the download script:
- grch37_spidex_public_noncommercial_-v1_0-.tab.gz (req. download license and the company shut down - describe in docs)
- grch37_genbank_haplogroup_-2015-08-01-.vcf.gz (MT freq built by us - will add to small reference repo)
- grch37_anon-swegen_str_nsphs_-1000samples-.vcf.gz (require license - describe in docs)
- grch37_cadd_whole_genome_snvs_-v1.4-.tsv.gz (add to download)
- grch37_cust003-cmms-red-pen_-2017-.tsv (info in Scout - will add to small reference repo )
- grch37_scout_exons_-2017-01-.bed (info in Scout - will add to small reference repo )
- hg19_human_excl_-0.7.6-.tsv [default in definition file] (From delly: https://github.com/dellytools/delly/tree/master/excludeTemplates - add to download)
- grch37_anon_swegen_snp_-2016-10-19-.tab.gz [default in definition] (require license - describe in docs)
- vcfanno_headerLines_-v1.0-.txt (built by us - will add to small reference repo)
- grch37_dbnsfp_-v3.5a-.txt.gz [default in definition] (Already part of download [dbnsfp])
- vcfanno_custom_-v1.0-.lua (built by us - will add to small reference repo)
- grch37_svdb_query_clingen_ngi_-v1.0.0-.vcf (built by clinical genetics - will add to small reference repo after ok)
- grch37_svdb_query_clingen_cgh_pathogenic_-v1.0.0-.vcf (built by clinical genetics - will add to small reference repo after ok)
- grch37_cadd_gnomad.genomes.r2.0.1_-v1.4-.tsv.gz (add to download)
- grch37_cadd_to_vcf_header_-1.0-.txt [default in definition] (built by us - will add to small reference repo)
- grch37_svdb_query_clingen_cgh_benign_-v1.0.0-.vcf (built by clinical genetics - will add to small reference repo after ok, and removal of GT fields)
- grch37_mip_sv_svdb_export_-2018-10-09-.vcf [not part of template file] (local SV freq, might be ok to add to a repo (sharing and size constraints))
- grch37_loqusdb_snv_indel_-2018-12-18-.vcf.gz (local SNV/INDELS freq , might be ok to add to a repo (sharing and size constraints))
- grch37_svdb_query_decipher_-v1.0.0-.vcf (built by clinical genetics - will add to small reference repo after ok)
- grch37_swegen_concat_sort_-20170830-.vcf [not part of template file] (SV freq file require license - describe in docs)
- grch37_gatk_merged_reference_samples.txt [not part of template file, includes paths to vcfs] (GATK exome add in files, describe in docs)

**Describe the solution you'd like**
Either make them part of the download script or document how they can be obtained. Some of them might be non-essential or highly specific to the activities at clinical genomics in which case we should consider removing them from the template.

**Comment by henrikstranneheim** [comment]
Fixed by #829 #847 #845 #844 #832
