### ISSUE TITLE
Improved reference genome

### ISSUE THREAD

**Issue by vwirta** [Clinical-Genomics/MIP#843]
**Is your feature request related to a problem? Please describe.**
The reference genome we are using is not perfect and does not include all sequences in the genome

**Describe the solution you'd like**
We should add the missing sequences into the reference genome we use, for example when we switch to hg38. See figure 5 in Ameur et al, linked below.

**Describe alternatives you've considered**
-
**Additional context**
https://www.ncbi.nlm.nih.gov/pubmed/30304863

![image](https://user-images.githubusercontent.com/2646553/58236430-2ba49d00-7d43-11e9-8090-f2acdeedfb03.png)

**Comment by henrikstranneheim** [comment]
Stale
