### ISSUE TITLE
mip install EPERL_5.26=success: command not found

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#851]
**Describe the bug**
The success check in the installtion scripts fails with "EPERL_5.26=success: command not found"

**To Reproduce**
1. perl git/MIP/mip install rd_dna --install eperl_5.26 --envn eperl_5.26=[test]
2. bash mip.sh
3. Check output for: "mip.sh: line 76: EPERL_5.26=success: command not found"

**Expected behavior**
No error message

**Screenshots**

**Software version (please complete the following information):**
 - MIP: [e.g. 7.0.9]

**Comment by jemten** [comment]
Done!
