### ISSUE TITLE
Add chromograph

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/MIP#905]
**Is your feature request related to a problem? Please describe.**
Add https://github.com/mikaell/chromograph for creating visualization images for Scout

**Describe the solution you'd like**
Test installing chromograph and creating static images using rhocall output data and tiddit_cov output data

**Comment by dnil** [comment]
Prereq:
- [ ]  Update rhocall to v0.5.1
- [ ] Adjust rhocall workflow to produce bed & wig files, along the lines of 
```
rhocall viz --wig --out_dir rhocall --aftag GNOMADAF --rho F0010931_sorted_md_brecal_haptc_vrecal_comb_BOTH.roh F0010931_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_frqf_vep_parsed_snpeff_ranked_BOTH.vcf
```
This is for a singleton case, otw use split vcfs. Ideally use non-frqf-files to have also the common pop SNVs to work with. 
- [ ] Add [UPD](https://github.com/bjhall/upd) for trios. Sth like 
```
upd --vcf input.vcf.gz --proband PB_ID --mother MOTHER_ID --father FATHER_ID regions --out upd_regions.bed
upd --vcf input.vcf.gz --proband PB_ID --mother MOTHER_ID --father FATHER_ID sites --out upd_sites.bed
```

**Comment by jemten** [comment]
Chromograph was added  #976

**Comment by henrikstranneheim** [comment]
Done
