### ISSUE TITLE
More sophisticated update of config after installation

### ISSUE THREAD

**Issue by jemten** [Clinical-Genomics/MIP#928]
**Is your feature request related to a problem? Please describe.**
When installing MIP there is an option to update the MIP config automatically. Currently the script simply replaces all occurrences of the old environment name with new one through a perl one liner (one for each conda environment). While that works it can lead to problems if the existing environment name is overly general. 

**Describe the solution you'd like**
Create a script called something like 'update_analysis_config.pl' that loads the template or existing config yaml and operates only on predefined keys in the config. This script can then be called in the installation file, mip.sh, with appropriate options.

**Comment by henrikstranneheim** [comment]
We will skip this for now
